- app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt
There may be a race condition where the service itself is stopping due to missing consent, but we still get an event causing:
```
kotlin.UninitializedPropertyAccessException: lateinit property serviceScope has not been initialized
at eu.darken.sdmse.automation.core.AutomationService.onAccessibilityEvent(AutomationService.kt:139)
at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2081)
at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2284)
```
> Automation: If ACS consent is missing, skip events and submissions.

- app-common-io/src/main/java/eu/darken/sdmse/common/storage/StorageEnvironment.kt
> Core: Fix NPE when accessing and converting Context.externalCacheDirs

- app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt
If the device is rooted, no inaccessible cache data will be generated, so no data items, no task and no automation if rooted :)
Closes #23
> AppCleaner: Don't submit automation tasks if there are no inaccessible caches.

- app/src/main/res/layout/dashboard_fragment.xml
> Dashboard: Make FAB round so there is a gap to the bottombar.

- app/src/main/java/eu/darken/sdmse/setup/accessibility/AccessibilitySetupCardVH.kt
- app/src/main/java/eu/darken/sdmse/setup/accessibility/AccessibilitySetupModule.kt
- app/src/main/res/layout/setup_accessibility_item.xml
- app/src/main/res/values/strings.xml
> Setup: Add hint for MIUI devices about Autostart and ACS

- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/local/LocalGateway.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/saf/SAFGateway.kt
Especially lookup(...) performance was out of balance.
> Improve IO performance by reducing logging when not in trace-mode.

- app-common-io/src/main/java/eu/darken/sdmse/common/root/javaroot/JavaRootClient.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/root/javaroot/JavaRootConnectionImpl.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/root/javaroot/JavaRootHost.kt
- app-common-root/src/main/java/eu/darken/sdmse/common/root/javaroot/internal/RootIPCReceiver.kt
- app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/items/DebugCardVH.kt
- app/src/main/res/layout/dashboard_debug_item.xml
> Fix root access not release mode

- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/local/LocalGateway.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/saf/SAFGateway.kt
- app-common/src/main/java/eu/darken/sdmse/common/debug/Bugs.kt
- app/src/gplay/java/eu/darken/sdmse/common/debug/autoreport/bugsnag/BugsnagLogger.kt
- app/src/main/java/eu/darken/sdmse/App.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardFragment.kt
Should make general search/path walking operations faster.
> Logging improvements

- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt
The ACS based code execution path worked on the unfiltered list of pkgs. Now we filter globally and pass the filtered list of pkgs along.
Fixes #67
> AppCleaner: Fix app exclusions only applying when using root.

- app/src/main/java/eu/darken/sdmse/setup/SetupFragment.kt
- app/src/main/res/values/strings.xml
> Setup: More helpful error message if documents ui app is disabled.

- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/PkgExtensions.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/features/InstallerInfo.kt
- app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt
- app/src/main/java/eu/darken/sdmse/main/core/GeneralSettings.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupEvents.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupFragment.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupFragmentVM.kt
- app/src/main/java/eu/darken/sdmse/setup/accessibility/AccessibilitySetupCardVH.kt
- app/src/main/java/eu/darken/sdmse/setup/accessibility/AccessibilitySetupModule.kt
- app/src/main/java/eu/darken/sdmse/setup/accessibility/AccessibilityToolsHelper.kt
- app/src/main/res/drawable/ic_baseline_warning_24.xml
- app/src/main/res/layout/setup_accessibility_item.xml
- app/src/main/res/values/strings.xml
If the app is side-loaded, the user needs:
* Try enabling our accessibility service once
* See the "Restricted settings" dialog
* Go to our app settings, but not directly, the system needs to open the details screen
* Allow restricted settings in the context menu
* Go back to the accessibility settings and enable SD Maid's service
Fixes #57
> Setup: Help the user with Android 13+ restrictions for side-loaded apps.

- app-common-io/src/main/java/eu/darken/sdmse/common/storage/SAFMapper.kt
If the mapping fails we shouldn't crash, but just continue without having it mapped.
```
java.lang.NullPointerException
at eu.darken.sdmse.common.storage.StorageVolumeX.getRootUri(StorageVolumeX.kt:163)
at eu.darken.sdmse.common.storage.StorageVolumeX.getTreeUri(StorageVolumeX.kt:173)
```
Device was an OPPO CPH1853 @ Android 8.1.0 (CPH1853EX_11_A.39) First volume was normal, internal storage, second storage was missing a UUID to identify it.
```
Target storageVolumes for LocalPath(/storage/emulated/0) is StorageVolumeX(uuid=null, directory=/storage/emulated/0, userlabel=Internal shared storage, volumeX=StorageVolume: Internal shared storage, )
Target storageVolumes for LocalPath(/dev/null) is StorageVolumeX(uuid=null, directory=/dev/null, userlabel=SD card, volumeX=StorageVolume: SD card, …
```
> Core: Add try-catch guards to SAFMapper to handle edge cases.

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/VivoAPI29PlusSpecs.kt
```
Current node hierarchy:
crawl():0: className=android.widget.FrameLayout, text='null', isClickable=false, isEnabled=true, viewIdResourceName=null, pkgName=com.android.settings
crawl():-1: className=android.widget.ImageView, text='null', isClickable=true, isEnabled=true, viewIdResourceName=vivo:id/holdingImg, pkgName=com.android.settings
crawl():-1: className=android.widget.TextView, text='App info', isClickable=true, isEnabled=true, viewIdResourceName=vivo:id/main, pkgName=com.android.settings
crawl():-1: className=android.widget.Button, text='null', isClickable=true, isEnabled=true, viewIdResourceName=null, pkgName=com.android.settings
crawl():-1: className=android.widget.ListView, text='null', isClickable=false, isEnabled=true, viewIdResourceName=android:id/list, …
```
> AppCleaner: Add ACS matching for VIVO

- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/APathExtensions.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/PathTreeFlow.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/local/LocalGateway.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/local/root/FileOpsHost.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/core/saf/SAFGateway.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCrawler.kt
Fixes #83
Not the solution I hoped for, but I think this is a bug on the OS side that I can't fix.
> Improve IO resiliance and handle weird errors smoother

- app-common-io/src/main/java/eu/darken/sdmse/common/user/UserManager2.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataAppAsecModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataAppLibModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataAppModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataAppPrivateModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataSDExt2Module.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataSystemCEModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataSystemDEModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/DataSystemModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/PrivateDataLegacyModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/priv/PrivateDataModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicDataModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicMediaModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicObbModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/SdcardsModule.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/generic/TempFilesFilter.kt
> Handle credential encrypted paths in multi user setups

- app/src/main/java/eu/darken/sdmse/common/debug/recording/core/RecorderModule.kt
> Place debug logs in SD Maids public cache folder

- app/src/main/java/eu/darken/sdmse/main/ui/MainActivity.kt
- app/src/main/java/eu/darken/sdmse/main/ui/MainActivityVM.kt
> Keep screen on while tasks are active.

- app-common/src/main/java/eu/darken/sdmse/common/debug/Bugs.kt
- app-common/src/main/java/eu/darken/sdmse/common/sharedresource/SharedResource.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/sieves/json/JsonBasedSieve.kt
About 3x in some cases :)
> execute() after 53318ms
> execute() after 17975ms
> Improve AppCleaner scan performance

- app-common-io/src/main/java/eu/darken/sdmse/common/storage/StorageVolumeX.kt
- app/src/main/java/eu/darken/sdmse/setup/saf/SAFSetupModule.kt
Secondary user profiles may not have access to the external sdcard.
> Only ask for permission for mounted storage.

- app-common/src/main/res/values/strings.xml
- app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleanerSettings.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/PostProcessorModule.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsFragment.kt
- app/src/main/res/drawable/folder_lock_outline.xml
- app/src/main/res/drawable/ic_file_chart_outline_24.xml
- app/src/main/res/drawable/ic_file_clock_outline_24.xml
- app/src/main/res/layout/view_preference_seekbar.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appcleaner.xml
> AppCleaner filter for cache size and age

- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
> AppControl: Fix infinite loop when changing sortmodes.

- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppInfo.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppInfoExtensions.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/tasks/AppControlTask.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/uninstall/UninstallException.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/uninstall/UninstallTask.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/uninstall/Uninstaller.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragmentVM.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionDialogVM.kt
- app/src/main/res/layout/appcontrol_list_fragment.xml
- app/src/main/res/values/strings.xml
Follow up to #220 by @yurtemre7
> Improve uninstall success/failure detection

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt
Return to the correct SD Maid screen so we don't always end up on the main dashboard.
> AppCleaner: Fix back button behavior when using accessibility service

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt
Remove Xiaomi edge-case behavior. 
Based on user feedback [via Discord](https://discord.com/channels/548521543039189022/1047079350157193236/1099818985203191838), this edge-case may no longer exist.
> AppCleaner: Do double back-press on all ROMs 

- app/src/main/assets/clutter/db_clutter_markers.json
> Add SMAPI as owner for StardewValley folder.

- app/src/main/java/eu/darken/sdmse/main/ui/settings/support/SupportFragment.kt
- app/src/main/java/eu/darken/sdmse/main/ui/settings/support/SupportFragmentVM.kt
- app/src/main/res/xml/preferences_support.xml
Why the fuck do some devices have no browser... Nokia C01 Plus???
> Clean  up support screen and catch ActivityNotFound exceptions

- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt
Specifically fix that package based exclusions did not prevent the AppCleaner scanner from looking up files based on FileForensics ownership. Previously we only skipped the paths that directly mapped to an installed app, but not custom paths that are only known to belong to an app after doing "file forensics" on it.
Excluding apps like in #245 should now prevent SD Maid from attempting to scan it in any way.
> Allow SD Maid to skip more AppCleaner work when using app exclusions

- app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recording/core/RecorderService.kt
Make it non-dismissible while active.
Provide better space to show the log path.
> Improve debug log notification

- app/src/main/assets/expendables/db_hidden_caches_files.json
- app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleanerSettings.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/TelegramFilter.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ViberFilter.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/WeChatFilter.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/sieves/dynamic/DynamicSieve.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/AppJunkExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appcleaner.xml
- app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/BugReportingFilterTest.kt
- app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/HiddenFilterTest.kt
- app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ThumbnailsFilterTest.kt
- app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ViberFilterTest.kt
- app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/WeChatFilterTest.kt
- app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/sieves/dynamic/DynamicSieveTest.kt
> AppCleaner: Add Viber chat app specific cleaning and improve existing filters.

- app/src/main/AndroidManifest.xml
> Core: Allow SD Maid to use more memory.

- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/actions/ExclusionActionDialog.kt
> Hide the SystemCleaner option from package exclusions as they don't work.

- app/src/main/res/layout/appcleaner_dashboard_item.xml
- app/src/main/res/layout/corpsefinder_dashboard_item.xml
- app/src/main/res/layout/dashboard_dataarea_item.xml
- app/src/main/res/layout/dashboard_setup_item.xml
- app/src/main/res/layout/dashboard_update_item.xml
- app/src/main/res/layout/systemcleaner_dashboard_item.xml
> Adjust dashboard button margins to prevent overlap.

- app/src/main/assets/clutter/db_clutter_markers.json
> Remove specific match for log_1 that caused it to be flagged as keeper.

- app/src/main/java/eu/darken/sdmse/appcleaner/ui/list/AppCleanerListRowVH.kt
- app/src/main/java/eu/darken/sdmse/common/ui/ViewExtensions.kt
> AppCleaner: Fix click deadzone on app icon.

- app/src/main/AndroidManifest.xml
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinderSettings.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/tasks/UninstallWatcherTask.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/watcher/ExternalWatcherResult.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/watcher/ExternalWatcherTask.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/watcher/ExternalWatcherTaskReceiver.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/watcher/UninstallWatcherNotifications.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/watcher/UninstallWatcherReceiver.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_corpsefinder.xml
> CorpseFinder: Uninstall watcher related notifications with optional actions.

- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentFragmentVM.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentItemVH.kt
- app/src/main/java/eu/darken/sdmse/common/MimeTypeTool.kt
- app/src/main/java/eu/darken/sdmse/common/coil/PathPreviewFetcher.kt
- app/src/main/res/layout/analyzer_content_item_vh.xml
- app/src/main/res/xml/file_provider_paths.xml
> StorageAnalyzer: Support for opening files from storage browser.

- app-common-io/src/main/java/eu/darken/sdmse/common/files/GatewaySwitch.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/storage/PathMapper.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScanner.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScannerExtensions.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/misc/PortableModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicDataModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicObbModule.kt
- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/SdcardsModule.kt
- app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt
- app/src/main/java/eu/darken/sdmse/setup/saf/SAFSetupModule.kt
- app/src/test/java/eu/darken/sdmse/analyzer/core/StorageScannerExtensionsTest.kt
- app/src/test/java/eu/darken/sdmse/analyzer/core/StorageScannerExtensionsTest2.kt
- app/src/test/java/eu/darken/sdmse/analyzer/core/TestApp.kt
> StorageAnalyzer: Support mixed path lookups (SAF+LOCAL)

- app-common/src/main/java/eu/darken/sdmse/common/AndroidModule.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt
- app/src/main/java/eu/darken/sdmse/common/deviceadmin/DeviceAdminManager.kt
> AppCleaner: Better handling of device admin apps on MIUI

- app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScanner.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/storage/categories/SystemCategory.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/StorageContentFragmentVM.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/categories/SystemCategoryVH.kt
Allow for some more browsing even if inaccessible.
> StorageAnalyzer: Improve UI

- app-common/src/main/res/values/strings.xml
- app/src/main/java/eu/darken/sdmse/exclusion/core/types/Exclusion.kt
- app/src/main/java/eu/darken/sdmse/exclusion/core/types/PkgExclusion.kt
- app/src/main/java/eu/darken/sdmse/exclusion/core/types/SegmentExclusion.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/editor/path/PathEditorEvents.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/editor/pkg/PkgExclusionEvents.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/editor/segment/SegmentExclusionEditorOptions.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/editor/segment/SegmentExclusionEvents.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/editor/segment/SegmentExclusionFragment.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/editor/segment/SegmentExclusionVM.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListAdapter.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListFragment.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListFragmentVM.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/types/PackageExclusionVH.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/types/PathExclusionVH.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/types/SegmentExclusionVH.kt
- app/src/main/res/drawable/ic_segment_24.xml
- app/src/main/res/drawable/ic_shield_plus_24.xml
- app/src/main/res/layout/exclusion_editor_path_fragment.xml
- app/src/main/res/layout/exclusion_editor_pkg_fragment.xml
- app/src/main/res/layout/exclusion_editor_segment_fragment.xml
- app/src/main/res/layout/exclusion_list_fragment.xml
- app/src/main/res/layout/exclusion_list_item_segment.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
Manual segment-based/partial exclusions.
e.g. you can create the exclusion `ndroid/Dat` to exclude `/sdcard/Android/data/something`.
> Exclusions: Support for manual exclusions

- app/src/main/res/xml/preferences_appcleaner.xml
Thanks, via Discord:
https://discord.com/channels/548521543039189022/1047079350157193236/1116294422708109492
> AppCleaner: Fix swapped settings labels.

- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsFragment.kt
> AppCleaner: Fix minimum size setting saving the wrong values

- app-common/src/main/res/values/strings.xml
- app/src/main/java/eu/darken/sdmse/analyzer/core/Analyzer.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/content/ContentDeleteTask.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/device/DeviceStorage.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/device/DeviceStorageScanner.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentAdapter.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentFragment.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentFragmentVM.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentGroupVH.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentItemEvents.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentItemVH.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/device/DeviceStorageFragmentVM.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/device/DeviceStorageItemVH.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListRowVH.kt
- app/src/main/java/eu/darken/sdmse/common/lists/selection/ItemSelectionMod.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListFragment.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/types/PackageExclusionVH.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/types/PathExclusionVH.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/types/SegmentExclusionVH.kt
- app/src/main/res/layout/analyzer_content_item_vh.xml
- app/src/main/res/layout/analyzer_device_vh.xml
- app/src/main/res/menu/menu_analyzer_content_list_cab.xml
+some more polish on general selection logic.
> StorageAnalyzer: Support for multi-item selection

- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicMediaModule.kt
- app/src/main/java/eu/darken/sdmse/setup/storage/StorageSetupModule.kt
Adjust permission rationale and try to set up partial access to Android/media
> AndroidTV: Improve storage detection & support.

- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionViewModel.kt
> AppControl: Support for enabling/disabling apps via Shizuku

- app-common-io/src/main/aidl/eu/darken/sdmse/common/pkgs/pkgops/ipc/PkgOpsConnection.aidl
- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/ipc/PkgOpsClient.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/ipc/PkgOpsHost.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/user/UserManagerExtensions.kt
- app-common/src/main/java/eu/darken/sdmse/common/permissions/Permission.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/items/SetupCardVH.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupHealer.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupManager.kt
- app/src/main/java/eu/darken/sdmse/setup/automation/AutomationSetupModule.kt
- app/src/main/java/eu/darken/sdmse/setup/notification/NotificationSetupModule.kt
- app/src/main/java/eu/darken/sdmse/setup/root/RootSetupModule.kt
- app/src/main/java/eu/darken/sdmse/setup/saf/SAFSetupModule.kt
- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
- app/src/main/java/eu/darken/sdmse/setup/storage/StorageSetupModule.kt
- app/src/main/java/eu/darken/sdmse/setup/usagestats/UsageStatsSetupModule.kt
- app/src/main/res/layout/dashboard_setup_item.xml
- app/src/main/res/values/strings.xml
Can automatically fix setup issues if Shizuku or Root is available.
Re #39
> Setup: Introduce `SetupHealer`

- app/src/main/java/eu/darken/sdmse/appcleaner/ui/AppCleanerDashCardVH.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/ui/CorpseFinderDashCardVH.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardFragment.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/MainActionItem.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/ui/SystemCleanerDashCardVH.kt
- app/src/main/res/layout/dashboard_fragment.xml
- app/src/main/res/menu/menu_main.xml
If some data is being provided with a delay we don't have an empty screen to look at :).
> Nicer dashboard loading behavior

- app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/service/ShizukuHost.kt
> Prevent R8 from optimizing ShizukHost away in release mode

- app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootHost.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootServiceClient.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/service/ShizukuHost.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/service/ShizukuServiceClient.kt
- app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/BaseRootHost.kt
- app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootHostInitArgs.kt
- app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootHostLauncher.kt
- app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootHostOptions.kt
- app-common-shizuku/src/main/java/eu/darken/sdmse/common/shizuku/service/internal/ShizukuHostLauncher.kt
- app-common-shizuku/src/main/java/eu/darken/sdmse/common/shizuku/service/internal/ShizukuHostOptions.kt
- app-common/src/main/java/eu/darken/sdmse/common/debug/logging/FileLogger.kt
- app/src/main/java/eu/darken/sdmse/common/compression/Zipper.kt
- app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/ui/RecorderActivity.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/ui/RecorderViewModel.kt
> Support recording root and shizuku output in debug logs

- app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerReceiver.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupHealer.kt
Wait for SetupHealer to attempt fixing permissions before running scheduled tasks.
> Improve Scheduler reliability

- app-common-io/src/main/java/eu/darken/sdmse/common/files/APathExtensions.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/APathLookupExtensions.kt
- app-common-io/src/test/java/eu/darken/sdmse/common/files/APathExtensionTest.kt
- app-common-io/src/test/java/eu/darken/sdmse/common/files/APathLookupExtensionTest.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/Analyzer.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/deleter/AppJunkDeleter.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCleaner.kt
* Smarter path batching
* Less progress updates
> Improve deletion performance

- app/src/main/java/eu/darken/sdmse/automation/core/common/StepProcessor.kt
> AppCleaner: Fix ACS step processor not exiting the while loop when a StepAbortException` is thrown.

- app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt
> IO: Fix access check failing for public storage.

- app/src/main/java/eu/darken/sdmse/appcontrol/core/uninstall/Uninstaller.kt
> Support hands-off uninstall via Shizuku

- app-common/src/main/java/eu/darken/sdmse/common/DeviceDetective.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/lge/LGESpecs.kt
- app/src/main/java/eu/darken/sdmse/automation/core/specs/SpecGenerator.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/core/RecorderModule.kt
> AppCleaner: Improve ACS debug output

- app/src/main/res/layout/onboarding_setup_fragment.xml
- app/src/main/res/layout/onboarding_versus_fragment.xml
- app/src/main/res/layout/onboarding_welcome_fragment.xml
- app/src/main/res/values/strings.xml
* Adjust texts, mention that pro status from SD Maid 1 can't be transfered
* Use animated SD Maid icon on welcome page
* Use happy icon on setup page
> Improve onboarding UI

- app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/SystemCleanerFilter.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/SystemCleanerFilterExtensions.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/ui/details/filtercontent/FilterContentViewModel.kt
Some QOL changes for things I noticed while debugging #517.
> SystemCleaner: Sort empty directory results by path and fix swapped descriptions

- app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ViberFilterTest.kt
Via https://github.com/d4rken-org/sdmaid-se/issues/204#issuecomment-1656320170
> AppCleaner: Fix typo in test-case.

- app/src/main/java/eu/darken/sdmse/main/ui/settings/SettingsIndexFragment.kt
- app/src/main/java/eu/darken/sdmse/main/ui/settings/SettingsViewModel.kt
> Hide "Sponsor" option from settings if user has pro upgrade

- app/src/main/assets/clutter/db_clutter_markers.json
Closes https://github.com/d4rken-org/sdmaid/issues/6036
Closes https://github.com/d4rken-org/sdmaid/issues/6065
Closes https://github.com/d4rken-org/sdmaid/issues/6083
> Update clutter db

- app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/SdcardsModule.kt
Remove duplicate checks, define access methods explicitly.
> Setup: Improve SD-card detection speed & reliability

- app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt
> IO: Fix createFile exists() check

- app/src/main/java/eu/darken/sdmse/main/ui/settings/general/GeneralSettingsFragment.kt
- app/src/main/res/xml/preferences_general.xml
> Remove hardcoded shortcut to upgrade screen

- app-common/src/main/res/values/strings.xml
- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/InaccessibleCacheProvider.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsFragment.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsViewModel.kt
- app/src/main/java/eu/darken/sdmse/common/preferences/CaveatPreferenceGroup.kt
- app/src/main/java/eu/darken/sdmse/common/preferences/CaveatPreferenceView.kt
- app/src/main/java/eu/darken/sdmse/common/preferences/PreferenceExtensions.kt
- app/src/main/java/eu/darken/sdmse/common/storage/StorageStatsManager2.kt
- app/src/main/res/layout/view_caveat_preference_group.xml
- app/src/main/res/layout/view_caveat_preference_view.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appcleaner.xml
> AppCleaner: Highlight settings that require "USAGE_STATS" permission to function correctly.

- app-common/src/main/java/eu/darken/sdmse/common/serialization/RegexAdapter.kt
> SystemCleaner: Fix custom filter serialization

- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardFragment.kt
> Dashboard: Fix SnackBar glitching the FAB after showing

- app-common/src/main/res/values/strings.xml
- app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/InaccessibleDeletionException.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsFragment.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsViewModel.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt
- app/src/main/java/eu/darken/sdmse/common/preferences/BadgedCheckboxPreference.kt
- app/src/main/java/eu/darken/sdmse/common/ui/SnackbarExtensions.kt
- app/src/main/java/eu/darken/sdmse/common/ui/ViewExtensions.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/ui/settings/CorpseFinderSettingsFragment.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/ui/settings/CorpseFinderSettingsViewModel.kt
- app/src/main/java/eu/darken/sdmse/main/ui/onboarding/setup/OnboardingSetupViewModel.kt
- app/src/main/java/eu/darken/sdmse/main/ui/settings/SettingsIndexFragment.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupFragment.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupModule.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupModuleExtensions.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupScreenOptions.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupViewModel.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCleaner.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/ui/settings/SystemCleanerSettingsFragment.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/ui/settings/SystemCleanerSettingsViewModel.kt
- app/src/main/res/drawable/bg_settings_badge.xml
- app/src/main/res/layout/view_preference_checkbox_badge_overlay.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appcleaner.xml
- app/src/main/res/xml/preferences_corpsefinder.xml
- app/src/main/res/xml/preferences_systemcleaner.xml
> Settings: Show which setup steps are required by each setting/feature

- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsFragment.kt
> AppCleaner: Show nicer values on minimum age and size sliders

- app/src/main/java/eu/darken/sdmse/main/core/motd/MotdApi.kt
- app/src/main/java/eu/darken/sdmse/main/core/motd/MotdRepo.kt
- motd/foss/beta/motd-de.json
- motd/foss/beta/motd-en.json
- motd/gplay/beta/motd-de.json
- motd/gplay/beta/motd-en.json
Rare edge-cases, and useful for testing.
> MOTD: Add a `maximumVersion` criteria

- app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleanerSettings.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/SpecRomType.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/alcatel/AlcatelSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/androidtv/AndroidTVSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/coloros/ColorOSSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/flyme/FlymeSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/huawei/HuaweiSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/lge/LGESpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/nubia/NubiaSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oneplus/OnePlusSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/realme/RealmeSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/samsung/SamsungSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/vivo/VivoSpecs.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsFragment.kt
- app/src/main/java/eu/darken/sdmse/common/preferences/EnumPreference.kt
- app/src/main/java/eu/darken/sdmse/common/preferences/PreferenceExtensions.kt
- app/src/main/java/eu/darken/sdmse/common/theming/ThemeMode.kt
- app/src/main/java/eu/darken/sdmse/common/theming/ThemeStyle.kt
- app/src/main/java/eu/darken/sdmse/main/core/GeneralSettings.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appcleaner.xml
> AppCleaner: Add setting to override operating system type detection (fix accessibility service on custom ROMs).

- app/src/main/java/eu/darken/sdmse/appcleaner/core/deleter/AppJunkDeleter.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/InaccessibleCache.kt
> AppCleaner: Sort deletion operations by size

- app/src/main/res/layout/appcontrol_dashboard_item.xml
> AppControl: Fix line-wrapping on dashboard card

- app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/ShizukuManager.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/PostProcessorModule.kt
> AppCleaner: If Shizuku is being used by SD Maid, then exclude it from cache clearing

- app/src/main/java/eu/darken/sdmse/common/uix/BottomSheetDialogFragment2.kt
- app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/create/ScheduleItemDialog.kt
- app/src/main/res/layout/scheduler_manager_create_dialog.xml
> Scheduler: Improve schedule creation behavior on Android TV devices

- app-common-io/build.gradle.kts
- app-common-pkgs/build.gradle.kts
- app-common-root/build.gradle.kts
- app-common-shell/build.gradle.kts
- app-common-shizuku/build.gradle.kts
- app-common-test/build.gradle.kts
- app-common/build.gradle.kts
- buildSrc/src/main/java/ProjectConfig.kt
> Clean up build scripts and use common extension to setup the defaults

- app/src/main/res/layout/corpsefinder_corpse_element_header.xml
- app/src/main/res/layout/systemcleaner_filtercontent_element_header.xml
> CorpseFinder/SystemCleaner: Change button width in details view to prevent overlap in some locales

- app/src/main/java/eu/darken/sdmse/main/ui/onboarding/privacy/OnboardingPrivacyFragment.kt
- app/src/main/java/eu/darken/sdmse/main/ui/onboarding/privacy/OnboardingPrivacyViewModel.kt
- app/src/main/res/layout/onboarding_privacy_fragment.xml
> Onboarding: Let users already toggle the MOTD check on/off during onboarding (on the privacy screen)

- PRIVACY_POLICY.md
> Update PRIVACY_POLICY to mention the update check mechanism

- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardFragment.kt
- app/src/main/res/layout/dashboard_fragment.xml
> Dashboard: Fix cut off progress text

- app/src/main/java/eu/darken/sdmse/main/core/GeneralSettings.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardFragment.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt
- app/src/main/java/eu/darken/sdmse/main/ui/settings/general/GeneralSettingsFragment.kt
- app/src/main/java/eu/darken/sdmse/main/ui/settings/general/OneClickOptionsDialog.kt
- app/src/main/res/layout/general_onetap_tools_dialog.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_general.xml
Either via Settings>General>Dashboard or a little hidden long-press on the floating action button ;).
> Dashboard: Settings to include/exclude tools from one-tap operations

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt
> AppCleaner: Fix progress display during ACS operations

- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
> Setup: Add missing Shizuku install check

- app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerNotifications.kt
- app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerWorker.kt
- app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerManagerFragment.kt
- app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerManagerViewModel.kt
- app/src/main/res/layout/scheduler_manager_fragment.xml
- app/src/main/res/menu/menu_scheduler_manager.xml
- app/src/main/res/values/strings.xml
+ a debug button to quick add test schedules.
> Scheduler: Add result notification to indicate success/failure

- app-common/src/main/res/values/strings.xml
- app/src/main/java/eu/darken/sdmse/common/ui/LayoutMode.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/core/DeduplicatorSettings.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListAdapter.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListEvents.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListFragment.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListLinearSubAdapter.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListLinearVH.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListViewModel.kt
- app/src/main/res/drawable/baseline_grid_view_24.xml
- app/src/main/res/drawable/baseline_list_alt_24.xml
- app/src/main/res/layout/deduplicator_list_fragment.xml
- app/src/main/res/layout/deduplicator_list_linear_item.xml
- app/src/main/res/layout/deduplicator_list_linear_sub_item.xml
- app/src/main/res/menu/menu_deduplicator_list.xml
> Deduplicator: Add alternative view modes (e.g. "linear list" vs grid) 

- app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerNotifications.kt
> Scheduler: Show additional details if the scheduler encounters an error

- app/build.gradle.kts
- app/src/main/res/resources.properties
> UI: Support Android 13+ system language picker

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/realme/RealmeLabels.kt
> AppCleaner: Support for RMX3231 (Android 11 Go)

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oneplus/OnePlusLabels31Plus.kt
> AppCleaner: Fix automation matching on OnePlus Android 13+ ROMs for German and English

- app-common/src/main/java/eu/darken/sdmse/common/ContextExtensions.kt
- app-common/src/main/java/eu/darken/sdmse/common/DeviceDetective.kt
Could close #853, might not actually be a oneplus rom issue.
> AppCleaner: Improve LineageOS detection

- app/src/main/java/eu/darken/sdmse/exclusion/core/LegacyImporter.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListEvents.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListFragment.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListViewModel.kt
- app/src/main/res/menu/menu_exclusions_list.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/eu/darken/sdmse/exclusion/core/ExclusionExtensionsTest.kt
- app/src/test/java/eu/darken/sdmse/exclusion/core/ExclusionStorageTest.kt
- app/src/test/java/eu/darken/sdmse/exclusion/core/LegacyImporterTest.kt
- app/src/test/java/eu/darken/sdmse/exclusion/core/types/PathExclusionTest.kt
- app/src/test/java/eu/darken/sdmse/exclusion/core/types/PkgExclusionTest.kt
> Exclusion: Support for importing SD Maid 1 exclusions.

- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListEvents.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt
- app/src/main/res/values/strings.xml
> AppControl: Show confirmation before enabling/disabling apps

- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt
Helps to narrow down causes if the dashboard is not loading.
> UI: Log the dashboard loading behavior

- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt
This reverts commit 29063595e72826909801fb2be04f599cee3a4d5b.
> Revert "UI: Log the dashboard loading behavior"

- app/src/main/java/eu/darken/sdmse/common/previews/PreviewEvents.kt
- app/src/main/java/eu/darken/sdmse/common/previews/PreviewFragment.kt
- app/src/main/java/eu/darken/sdmse/common/previews/PreviewViewModel.kt
- app/src/main/java/eu/darken/sdmse/common/uix/DialogFragment2.kt
- app/src/main/java/eu/darken/sdmse/common/uix/DialogFragment3.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/PreviewDeletionDialog.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/details/cluster/ClusterFragment.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListEvents.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListFragment.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListGridVH.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListLinearVH.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListViewModel.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardFragment.kt
- app/src/main/res/layout/preview_fragment.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/themes.xml
> Deduplicator: Fullscreen preview for thumbnails

- app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/FilterSource.kt
IllegalStateException due to not finding targets.
> SystemCleaner: Fix filter content deletion

- app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/AnrFilter.kt
The error dialog doesn't help the user and operations can just continue and this filter just doesn't match. Easier for the user.
So let's not pop an error dialog and just log a warning.
> SystemCleaner: If the ANR filter fails to initialize correctly, fail silently

- app/src/main/java/eu/darken/sdmse/common/MascotView.kt
- app/src/main/res/anim/anim_rotate.xml
> UI: Fix mascot scaling issues

- app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt
Some debug improvements related to #907
> ACS: Improve debug output to help fix multi-locale issues

- app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/PkgRepo.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControlScanTask.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/uninstall/Uninstaller.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt
> AppControl: Increase uninstaller's minimum timeout and calculate timeout based on app sizes

- app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerWorker.kt
> Scheduler: Update last execution time even if execution fails/aborts

- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/PkgExtensions.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionViewModel.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupViewModel.kt
- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupCardVH.kt
- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
- app/src/main/res/layout/setup_shizuku_item.xml
> Shizuku: Add button to open app if it's installed, enabled, but not running

- app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/ShizukuManager.kt
- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
Let's catch any errors any still emit null. Also don't activate the permission requester flow if the user has declined to use Shizuku.
> Setup: Fix dashboard hanging due to Shizuku not emitting a setup state

- app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/AppJunkDetailsViewModel.kt
> AppCleaner: Fix error when deleting the last app's cache from details

- app-common/src/main/res/values/strings.xml
- app/src/main/java/eu/darken/sdmse/common/EasterEggs.kt
> UI: More easter egg progress messages

- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/device/DeviceStorageItemVH.kt
- app/src/main/res/layout/analyzer_device_vh.xml
> StorageAnalyzer: Show IDs for SD-Cards and make it copyable

- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt
AppCleaner hangs on one user device (`samsung/a52xque/a52xq:14/UP1A.231005.007/A526U1UESCFXA1:user/release-keys`).
> Debug: Add more log output to troubleshoot AppCleaner hanging during scan on a device

- app/src/main/java/eu/darken/sdmse/common/debug/recorder/core/RecorderModule.kt
Prevent ANR if triggerFile path is resolved on main thread and IO is hanging.
> Debug: Prevent ANR if debug log is started

- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControlSettings.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/settings/AppControlSettingsFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/settings/AppControlSettingsViewModel.kt
- app/src/main/res/drawable/ic_run_24.xml
- app/src/main/res/drawable/ic_weight_24.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appcontrol.xml
- app/src/main/res/xml/preferences_index.xml
This makes the list of apps load much faster if neither information is desired.
Closes #994
> AppControl: Add settings to disable checking app sizes and activity status

- app-common/src/main/java/eu/darken/sdmse/common/ContextExtensions.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/app/AppDetailsFragment.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/device/DeviceStorageFragment.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/StorageContentFragment.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/AppJunkFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionDialog.kt
- app/src/main/java/eu/darken/sdmse/common/lists/RecyclerViewExtensions.kt
- app/src/main/java/eu/darken/sdmse/common/navigation/FragmentExtensions.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/ui/details/corpse/CorpseFragment.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/details/cluster/ClusterFragment.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListFragment.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListLinearVH.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardFragment.kt
- app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerManagerFragment.kt
- app/src/main/java/eu/darken/sdmse/setup/SetupFragment.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/ui/customfilter/editor/CustomFilterEditorFragment.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/ui/details/filtercontent/FilterContentFragment.kt
> AppControl: Show items in multi column grid on wider screens (or in landscape)

- app/src/main/java/eu/darken/sdmse/analyzer/core/device/DeviceStorage.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/device/DeviceStorageScanner.kt
- app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScanner.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/device/DeviceStorageItemVH.kt
- app/src/main/res/drawable/ic_usb_24.xml
- app/src/main/res/values/strings.xml
> Analyzer: Detect USB sticks as extra storage type and improve scanning

- app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/SAFDocFile.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/ipc/PkgOpsClient.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt
- app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt
- app/src/main/java/eu/darken/sdmse/automation/ui/AutomationControlView.kt
- app/src/main/java/eu/darken/sdmse/common/progress/ProgressBarView.kt
- app/src/main/res/layout/view_progressbar.xml
Nicer display and fixed a glitch where it would jump into "no progress mode".
> AppCleaner: Improve progress display behavior

- fastlane/metadata/android/en-US/full_description.txt
> Improve app store description

- app-common/src/main/java/eu/darken/sdmse/common/ContextExtensions.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/apps/AppsFragment.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentFragment.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/device/DeviceStorageFragment.kt
- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/StorageContentFragment.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/list/AppCleanerListFragment.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
- app/src/main/java/eu/darken/sdmse/common/navigation/FragmentExtensions.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/ui/list/CorpseFinderListFragment.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListFragment.kt
- app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardFragment.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/ui/list/SystemCleanerListFragment.kt
Span count calculation could return 0.
Fixes #1108
> Setup: Fix crash if screen has narrow aspect ratio

- app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/RecycleBinsFilter.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ThumbnailsFilter.kt
- app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/RecycleBinsFilterTest.kt
* `/sdcard/folder/<trash>`
* `/sdcard/Android/media/<pkg>/...`
> AppCleaner: Extend recycle-bins filter to top level folders and media

- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
This reverts commit d7325c58acaca1a8bc64e133d70befd10fdc0848.
Reverts #1106
> Revert "Shizuku: Don't hang on dashboard if Shizuku is not responding"

- fastlane/metadata/android/en-US/full_description.txt
> Change description and pray that it pleases Google Play

- app/src/main/java/eu/darken/sdmse/common/navigation/FragmentExtensions.kt
390 before, now needs at least 410 for multi columns
> UI: Larger minimum column size

- app/build.gradle.kts
> Build process: Adjust final APK naming scheme to be more F-Droid friendly

- app/src/main/java/eu/darken/sdmse/main/core/release/ReleaseManager.kt
- app/src/main/java/eu/darken/sdmse/main/ui/release/BetaGoodbyeFragment.kt
- app/src/main/java/eu/darken/sdmse/main/ui/release/BetaGoodbyeViewModel.kt
- app/src/main/res/layout/beta_goodbye_fragment.xml
e.g.: Only show it for release builds, not for beta builds.
> Improve V1.0 release screen behavior

- app/src/foss/res/values-de/strings.xml
- app/src/foss/res/values/strings.xml
- app/src/gplay/res/values-de/strings.xml
- app/src/gplay/res/values/strings.xml
- app/src/main/java/eu/darken/sdmse/main/core/release/ReleaseManager.kt
- app/src/main/java/eu/darken/sdmse/main/ui/release/BetaGoodbyeFragment.kt
- app/src/main/res/layout/beta_goodbye_fragment.xml
Show it for pre-releases too and explain how to switch without re-installing.
> Improve release party screen

- app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt
If the click target is disabled, all other buttons are disabled too, and it's a system app and we have Android 14, then don't retry, just throw `PlanAbort` and go to the next app.
Fixes #1178
> AppCleaner: Don't retry system apps where "Clear cache" is disabled

- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentViewModel.kt
> Analyzer: Improve debug output to investigate issues when opening files

- app/src/main/java/eu/darken/sdmse/main/core/motd/MotdRepo.kt
> Prevent MOTD check from happening before onboarding is complete

- app/src/main/java/eu/darken/sdmse/App.kt
> If debug mode is disabled, then also disable dry-run mode

- app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/PackageManagerExtensions.kt
> Fix crash when retrieving app data on Android 12 and lower when using Shizuku or Root

- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupCardVH.kt
- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
- app/src/main/res/values/strings.xml
> Setup: If root access is available show additional explanation for Shizuku

- app/schemas/eu.darken.sdmse.stats.core.db.ReportsRoomDb/1.json
- app/src/main/java/eu/darken/sdmse/stats/core/AffectedApp.kt
- app/src/main/java/eu/darken/sdmse/stats/core/AffectedPath.kt
- app/src/main/java/eu/darken/sdmse/stats/core/Report.kt
- app/src/main/java/eu/darken/sdmse/stats/core/StatsRepo.kt
- app/src/main/java/eu/darken/sdmse/stats/core/db/AffectedFilesDao.kt
- app/src/main/java/eu/darken/sdmse/stats/core/db/AffectedPathEntity.kt
- app/src/main/java/eu/darken/sdmse/stats/core/db/ReportsDatabase.kt
- app/src/main/java/eu/darken/sdmse/stats/ui/paths/AffectedPathsAdapter.kt
- app/src/main/java/eu/darken/sdmse/stats/ui/paths/AffectedPathsFragment.kt
- app/src/main/java/eu/darken/sdmse/stats/ui/paths/AffectedPathsViewModel.kt
- app/src/main/java/eu/darken/sdmse/stats/ui/paths/elements/AffectedPathVH.kt
- app/src/main/java/eu/darken/sdmse/stats/ui/paths/elements/AffectedPathsHeaderVH.kt
- app/src/main/java/eu/darken/sdmse/stats/ui/reports/ReportsFragment.kt
- app/src/main/java/eu/darken/sdmse/stats/ui/reports/ReportsViewModel.kt
- app/src/main/res/layout/stats_affected_paths_fragment.xml
- app/src/main/res/layout/stats_affected_paths_header_item.xml
- app/src/main/res/layout/stats_affected_paths_path_item.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
> Stats: Show paths that were affected by an operation

- app-common-io/src/main/java/eu/darken/sdmse/common/files/APathExtensions.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/files/APathLookupExtensions.kt
- app-common-io/src/test/java/eu/darken/sdmse/common/files/APathExtensionTest.kt
- app/src/main/java/eu/darken/sdmse/common/coil/PathPreviewFetcher.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/CommonFilesCheck.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/checksum/ChecksumSleuth.kt
Anywhere we load previews, it should now be able to load preview for .apk files if it is possible to access without root.
> Support previews (show icons) for .apk

- app/src/main/AndroidManifest.xml
- app/src/main/java/eu/darken/sdmse/main/core/taskmanager/TaskWorker.kt
- app/src/main/java/eu/darken/sdmse/main/core/taskmanager/TaskWorkerControl.kt
- app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerWorker.kt
> Core: Improve background execution reliability

- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListFragment.kt
- app/src/main/java/eu/darken/sdmse/exclusion/ui/list/ExclusionListViewModel.kt
- app/src/main/res/menu/menu_exclusions_list.xml
- app/src/main/res/values/strings.xml
Little checkbox in the menu to hide default exclusions.
> Exclusions: Hide default exclusions behind option in menu

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLabler.kt
On large apps, the system may take a while to load their stats. This is first retrieved when the system gets the data to display it on screen. The on-the-fly labeler also retrieves the data to compare against though. Because the labeler does it on-demand this, but each time. Requesting the size repeatedly, if the system is already working on it, can delay the process.
This PR changes the labeler, so the size is only retrieved once per app.
Fixes #1304
> AppCleaner: Fix accessibility based cache deletion failing on large apps

- app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootHostLauncher.kt
- app-common-shizuku/src/main/java/eu/darken/sdmse/common/shizuku/service/internal/ShizukuHostLauncher.kt
> Core: Don't crash if there is an issue with Root or Shizuku

- fastlane/metadata/android/de-DE/changelogs/default.txt
- fastlane/metadata/android/en-US/changelogs/default.txt
This is usually the first text that is visible on Google Play. Let's to adjust expectations about support a bit.
> Adjust default changelog text

- app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentItemVH.kt
> Analyzer: Allow selection of top-level directories

- app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/sources/HiddenPkgsSource.kt
Reading APKs of hidden packages is time consuming. We can skip all packages that are already available through normal APIs.
> Pkgs: Faster loading of hidden app packages on rooted devices

- app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/miui/MIUILabels.kt
- app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/miui/MIUISpecs.kt
> AppControl: Add Force-Stop via ACS on MIUI ROMs

- app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/EmptyDirectoryFilter.kt
> SystemCleaner: Fix empty directories not being detected on large sdcards

- app/src/main/res/layout/dashboard_review_item.xml
> Improve text wrapping on the "Review Me" card in multi-column layout

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLabler.kt
Check for Non-Breaking-Space when generating dynamic labels.
> AppCleaner: Make text matching during accessibility based deletion more resilient

- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsFragment.kt
- app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/SizeInputDialog.kt
- app/src/main/java/eu/darken/sdmse/deduplicator/ui/settings/DeduplicatorSettingsFragment.kt
- app/src/main/res/layout/view_preference_input_size.xml
Size can now be set both by using the slider, and by manually typing in a value, e.g. `123 KB` or `55 MB` or `98 B`
Closes #1438
Closes #1484
> AppCleaner, Deduplicator: Allow manual input for "minimum size"

- README.md
Address small typo in the description of AppControl
> Potential typo in readme.md

- app/src/main/java/eu/darken/sdmse/corpsefinder/ui/details/corpse/elements/CorpseElementHeaderVH.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/ui/list/CorpseFinderListRowVH.kt
- app/src/main/res/layout/corpsefinder_corpse_element_header.xml
- app/src/main/res/layout/corpsefinder_list_item.xml
* Highlight hints with different colors to draw more attention
* Rearrange layout
* Add little icon that indicates if the corpse is a file or a folder
> Improve CorpseFinder details screen

- app/src/main/java/eu/darken/sdmse/analyzer/core/device/DeviceStorageScanner.kt
- app/src/main/java/eu/darken/sdmse/common/storage/StorageStatsManager2.kt
> StorageAnalyzer: Fix invalid storage size being displayed for large SD-cards

- app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/DuplicatesScanner.kt
> Deduplicator: Fix default paths not being used if custom paths are not provided

- app-common/src/main/java/eu/darken/sdmse/common/BuildWrap.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppAsecFileCorpseFilter.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppLibCorpseFilter.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppSourceCorpseFilter.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppSourcePrivateCorpseFilter.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/DalvikCorpseFilter.kt
- app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/PrivateDataCorpseFilter.kt
Enable root-based filters for API35.
> CorpseFinder: Improve scan on Android 15

- app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCleanerSettings.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/PackageCacheFilter.kt
- app/src/main/java/eu/darken/sdmse/systemcleaner/ui/settings/SystemCleanerSettingsFragment.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_systemcleaner.xml
- app/src/test/java/eu/darken/sdmse/systemcleaner/core/filter/stock/PackageCacheFilterTest.kt
Cache files used by the system package management. See: https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/pm/PackageManagerServiceUtils.java;l=1345
> SystemCleaner: New filter for `/data/system/package_cache`

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt
Similar to the update HyperOS2 has for the Security-Center app (`com.miui.securitycenter`): The buttons are no longer clickable by the default action and seem to require a gesture. Buggy UI framework by Xiaomi?
See #1648 and PR #1652
Fixes #1691
> AppCleaner: Fix ACS based cache clearing on MIUI ROMs with new "Security-Center" update

- app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt
> AppCleaner: Gracefully handle missing USAGE_STATS permission

- app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/DuplicatesScanner.kt
> Deduplicator: Fix error when selecting root of public storage as custom search path

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt
In the 2 weeks I'm trying to fix this, Xiaomi updated their Security app again (╯°□°)╯︵ ┻━┻
* First it was a clickable TextView
* Then it was an unclickable RadioButton
* Now it is a TextView again, but it is unclickable too
`v10.6.5-250318.1.1` was still the unclickable RadioButton, some version after that, it is the unclickable TextView.
I've changed the matching to ignore the type and just look for the label. Less specific, might cause issues in the future, but I'm really tired of this.
> AppCleaner: Fix ACS based cache deletion on HyperOS with latest Security app

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/AppCleanerSpecGeneratorExtensions.kt
API30 has system apps with locked cache buttons too, e.g.: `realme/RMX2001EEA/RMX2001L1:11/RP1A.200720.011/1647528410735:user/release-keys`
```java
0: text='null', class=android.widget.FrameLayout, clickable=false, checkable=false enabled=true, id=null pkg=com.android.settings, identity=525b1a6, bounds=Rect(0, 0 - 1080, 2400)
-1: text='null', class=android.widget.LinearLayout, clickable=false, checkable=false enabled=true, id=null pkg=com.android.settings, identity=43bcf94, bounds=Rect(0, 0 - 1080, 2268)
--2: text='null', class=android.widget.FrameLayout, clickable=false, checkable=false enabled=true, id=null pkg=com.android.settings, identity=72eaa3d, bounds=Rect(0, 0 - 1080, 2268)
---3: text='null', class=android.widget.LinearLayout, clickable=false, checkable=false enabled=true, …
```
> AppCleaner: Improve detection for locked system apps on Android 11

- app-common-io/src/main/java/eu/darken/sdmse/common/adb/service/AdbHost.kt
- app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootHost.kt
- app-common/src/main/java/eu/darken/sdmse/common/debug/logging/FileLogger.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/core/Recorder.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/core/RecorderModule.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/core/RecorderService.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/ui/DebugRecorderCardVH.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/ui/LogFileAdapter.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/ui/RecorderActivity.kt
- app/src/main/java/eu/darken/sdmse/common/debug/recorder/ui/RecorderViewModel.kt
- app/src/main/res/layout/debug_recorder_activity.xml
- app/src/main/res/layout/debug_recorder_logfile_item.xml
* Use a "debug session directory", previously we a bit hacky string replace.
* Nicer debug log share screen with more details and better progress.
* Less error prone zip file creation in the share screen
> Improve debug log recording

- app/src/main/java/eu/darken/sdmse/automation/core/errors/AutomationCompatibilityException.kt
> AutomationCompatibilityException should include the current app version

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/StorageEntryFinder.kt
Last updates improved detection for large screen devices caused issues with normal detection.
Fixes #1736
Fixes #1737
> AppCleaner: Fix storage entry detection

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt
Longer delay before clicking "Clear cache".
Previously we missed the button because the animated dialog did not have settled yet.
> AppCleaner: Fix HyperOS ACS issues

- app/src/main/res/layout/appcontrol_list_fragment.xml
Filter pane layout should allow scrolling on screens with small vertical space.
+ Some layout polishing.
Fixes #1752
> AppControl: Fix scroll pane being inaccessible in landscape mode

- app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt
This change adds logging to the ClearCacheModule to provide better visibility into the animation state.
> AppCleaner: Add more logging to ClearCacheModule

- app/src/main/java/eu/darken/sdmse/common/ui/SizeParser.kt
> General: Support manual size input in Arabic

- app/src/main/java/eu/darken/sdmse/common/ui/AgeInputDialog.kt
- app/src/main/java/eu/darken/sdmse/common/ui/DurationParser.kt
Better parsing for more locales.
```bash
15:54:50.778 SDMSE:ViewPreferenceInputAgeBinding               D  Parsed 8 дн. to PT192H
15:54:52.759 SDMSE:ViewPreferenceInputAgeBinding               D  Parsed 0 ч. to PT0S
15:54:53.422 SDMSE:ViewPreferenceInputAgeBinding               D  Parsed 0 ч. to PT0S
15:54:54.228 SDMSE:ViewPreferenceInputAgeBinding               D  Parsed 1 день to PT24H
15:54:59.094 SDMSE:ViewPreferenceInputAgeBinding               D  Parsed 1 день to PT24H
15:55:00.552 SDMSE:ViewPreferenceInputAgeBinding               D  Parsed 2 дн. to PT48H
15:55:04.280 SDMSE:ViewPreferenceInputAgeBinding               D  Parsed 2 дн to PT48H
15:55:07.230 SDMSE:ViewPreferenceInputAgeBinding               D  Parsed 2 дн. to PT48H
15:55:12.065 SDMSE:ViewPreferenceInputAgeBinding …
```
> AppCleaner: Fix minimum file age input in Russian

- app-common/src/main/java/eu/darken/sdmse/common/datastore/PreferenceStoreMapper.kt
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- buildSrc/src/main/java/Versions.kt
Updated the versions of several dependencies, including Dagger, AndroidX Navigation, KSP, and Android Gradle Plugin.
> Update dependency versions

- app-common-io/src/main/java/eu/darken/sdmse/common/adb/shizuku/ShizukuManager.kt
- app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
Added "ADB" to the log tags for classes related to Shizuku functionality, making it clearer they are part of the ADB implementation.
> Logging: Improve ADB Shizuku tags

- app/src/main/java/eu/darken/sdmse/setup/saf/SAFSetupModule.kt
The `DocumentsUI` app is part of "Google Play system updates". A newer version (>= `331120000`) restricts access to `Android/data` and `Android/obb` even on Android 11 & 12 (API 30-32). This change adds a version check for `DocumentsUI` to correctly reflect its capabilities.
If the version is too new, or if the package information cannot be retrieved, assume access is restricted. The target SDK version check remains as a fallback.
Fixes https://github.com/d4rken-org/sdmaid-se/discussions/1762
> Setup: Check `DocumentsUI` version to determine SAF grantability

- .claude/settings.json
- app/build.gradle.kts
Proguard/R8 issue, see:
https://issuetracker.google.com/issues/374691245
Open since.... Oct 21, 2024 D:
> Fix Google Play variant build-issue
