d4rken-org/sdmaid-se

app-common-io/src/main/java/eu/darken/sdmse/common/files/core/local/LocalGateway.kt
File.canWrite() check is unreliable. File.delete() may still fail. If this happens, and we have root, retry with root.
Fixes #44
=> Core: Retry failed File.canDelete() with root if available.

app/src/main/java/eu/darken/sdmse/main/core/CurriculumVitae.kt
So we can later show the user extra information when we switch from BETA to RELEASE builds.
=> Track beta launches 

app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/InaccessibleCacheProvider.kt
=> Fix AppCleaner item count being off by 1 when inaccessible caches are listed

app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionDialogVM.kt
We can still crash despite using `getLaunchIntentForPackage`
```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.google.android.apps.dynamite/com.google.android.apps.dynamite.startup.StartUpActivity}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2179)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1812)
at android.app.ContextImpl.startActivity(ContextImpl.java:1091)
at android.app.ContextImpl.startActivity(ContextImpl.java:1062)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:411)
at eu.darken.sdmse.appcontrol.ui.list.actions.AppActionDialogVM$state$2$launchAction$2$1.invoke(AppActionDialogVM.kt:69)
```
=> Catch activity launch crash for appcontrol entries.

app-common-io/src/main/aidl/eu/darken/sdmse/common/files/local/root/DetailedInputSource.aidl, app-common-io/src/main/aidl/eu/darken/sdmse/common/files/local/root/FileOpsConnection.aidl, app-common-io/src/main/aidl/eu/darken/sdmse/common/pkgs/pkgops/root/PkgOpsConnection.aidl, app-common-io/src/main/aidl/eu/darken/sdmse/common/root/io/RemoteInputStream.aidl, app-common-io/src/main/aidl/eu/darken/sdmse/common/root/io/RemoteOutputStream.aidl, app-common-io/src/main/java/eu/darken/sdmse/common/files/SourceExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/root/DetailedInputSourceWrap.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/root/FileOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/root/FileOpsHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/root/LocalPathLookupsPayload.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/root/LocalPathPayload.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/root/PackageInfoPayload.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/root/PkgOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/root/PkgOpsHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/root/io/RemoteInputStreamExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/root/io/RemoteOutputStreamExtensions.kt
When getting installed packages for other users via root, we can exceed the IPC buffer size.
```
android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
```
This should fix #131 
At least the error is very similar
=> PkgOps: Stream installed package data to stay within buffer limits

app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/SdcardsModule.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt
For multi-user devices perform an additional check on corpses that reside in data areas where they are potentially shared between user profiles.
Fixes #156
=> Improve ownership detection for multi-user setups

app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt
If consent is not given, the service is not completely initialized, so the order here matters.
=> Fix accessibility service init crash.

app/src/main/res/layout/appcleaner_dashboard_item.xml, app/src/main/res/layout/appcontrol_dashboard_item.xml, app/src/main/res/layout/corpsefinder_dashboard_item.xml, app/src/main/res/layout/scheduler_dashboard_item.xml, app/src/main/res/layout/systemcleaner_dashboard_item.xml, app/src/main/res/xml/preferences_corpsefinder.xml
Remove view text and only use an icon (the full card can be clicked anyways).
This removes some overlapping between buttons in more verbose languages.
=> Tweak dashboard

app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt
If the user activated the accessibility service via a shortcut, the setup card on the dashboard now automatically dismisses.
=> Automatically refresh setup if accessibility service is launched without entering the setup.

app/src/main/assets/clutter/db_clutter_markers.json, app/src/main/assets/expendables/db_hidden_caches_files.json, app/src/main/assets/expendables/db_thumbnail_files.json, app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleanerSettings.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/RecycleBinsFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ThumbnailsFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/AppJunkExtensions.kt, app/src/main/java/eu/darken/sdmse/common/clutter/dynamic/NestedPackageV2Matcher.kt, app/src/main/java/eu/darken/sdmse/common/forensics/Owner.kt, app/src/main/res/drawable/ic_multimedia_24.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_appcleaner.xml, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/HiddenFilterTest.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/RecycleBinsFilterTest.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ThumbnailsFilterTest.kt
* Include folders in scan where the owner was dynamically matched, i.e. `_some.pkg` 
* Create additional "Thumbnails" filter
* Some additional performance gains due to refactoring too.
=> AppCleaner: Improve scan, include more types of folders.

app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt
According to GPlay tracking, onAccessibilityEvent can be called async? sus
=> Fix ACS init crash

app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/tasks/AppCleanerDeleteTask.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/AppJunkEvents.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/AppJunkFragment.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/AppJunkFragmentVM.kt
=> AppCleaner: Fix single path/filter type deletion always triggering ACS based deletion for inaccessible caches

app/src/main/java/eu/darken/sdmse/common/serialization/SerializedStorage.kt, app/src/main/java/eu/darken/sdmse/exclusion/core/ExclusionManager.kt, app/src/main/java/eu/darken/sdmse/exclusion/core/ExclusionStorage.kt, app/src/main/java/eu/darken/sdmse/scheduler/core/ScheduleStorage.kt, app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerManager.kt, app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerRestoreReceiver.kt, app/src/test/java/eu/darken/sdmse/common/exclusion/core/ExclusionStorageTest.kt, app/src/test/java/eu/darken/sdmse/scheduler/core/ScheduleStorageTest.kt
Use common base class to handle json-based storage and align edge-case handling: If the save-file is empty delete it and return null.
```java
java.io.EOFException: End of input
at com.squareup.moshi.JsonUtf8Reader.nextNonWhitespace(JsonUtf8Reader.java:1144)
at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:337)
at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:206)
at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:38)
at eu.darken.sdmse.common.files.local.JsonAdapterExtensionsKt.from(JsonAdapterExtensions.kt:33)
```
This does only seem to happen on boot restores 🤔 
```
1683447102661 D/SDMSE:Scheduler:Receiver:Restore: onReceive(android.app.ReceiverRestrictedContext@6fac6ca,Intent { act=android.intent.action.BOOT_COMPLETED …
```
=> Fix crash when json file is corrupted.

app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt, app/src/main/java/eu/darken/sdmse/common/debug/autoreport/DebugSettings.kt, app/src/main/java/eu/darken/sdmse/common/debug/recording/core/RecorderModule.kt
Store current log path in debug settings so we can append to the previous log file after a crash.
See #245
=> Fix debug log being incomplete after crashes

app/src/main/java/eu/darken/sdmse/setup/saf/SAFSetupModule.kt
i.e. no "Documents" app that consumes `ACTION_OPEN_DOCUMENT_TREE`
=> SAF: Workarounds for missing ACTION_OPEN_DOCUMENT_TREE support

app/build.gradle.kts, app/src/gplay/java/eu/darken/sdmse/common/debug/autoreport/GooglePlayReporting.kt
Even if bugsnag is disabled, use the relinker, otherwise setting bugsnag up for NOOP can still crash.
=> Fix native library linking crash

app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/elements/AppJunkElementHeaderVH.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/list/AppCleanerListRowVH.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionDialogVM.kt
realme narzo 30A (RMX3171) @ Android 11
```
java.lang.SecurityException: Not allowed to start activity Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:com.coloros.sauhelper flg=0x10000000 }
``
=> Don't crash if we are not allowed to open the system details for an app

app/src/main/java/eu/darken/sdmse/main/ui/settings/SettingsIndexFragment.kt, app/src/main/java/eu/darken/sdmse/setup/SetupFragment.kt, app/src/main/res/menu/menu_setup.xml, app/src/main/res/navigation/main_nav.xml, app/src/main/res/xml/preferences_index.xml
It's too niche to show it as main item in the first settings page. Can now be reached via context menu in the setup screen (but not on the very first onboarding).
=> Move details screen for available data areas

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalPathExtensions.kt
Remove extra canRead check. Doesn't seem necessary.
I don't see why this was necessary and it costs a lot of extra time when iterating files.
Theoretically we would abort early if we encounter a read error, but this does not seem to happen on real devices I tested with.
=> IO: Improve LocalPath scan performance

app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/automation/core/crawler/AccessibilityNodeExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/crawler/AutomationCrawler.kt
The crawler's window test never passed due to events being "empty" and so the process never continues as SD Maid can't confirm the right window is visible.
While the ACS event handling changed in API30+ and AccessibilityEvent are not longer pooled and recycled, we still need to copy the event or we encounter:
```java
Cannot perform this action on a not sealed instance.
```
and empty events. So despite .recycle() being a NOOP, events are stilled null'ed?
=> Fix AppCleaner ACS based deletion failing on fast API30+ devices

app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/categories/AppCategoryVH.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/categories/MediaCategoryVH.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/categories/SystemCategoryVH.kt, app/src/main/res/values/strings.xml
The rounding is confusing and does not deliver enough value. The progressbars deliver the same info and quicker.
Fixes #316
=> StorageAnalyzer: Remove category percentages

app/build.gradle.kts, app/src/main/java/eu/darken/sdmse/analyzer/core/content/ContentItem.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentItemVH.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/elements/AppJunkElementFileVH.kt, app/src/main/java/eu/darken/sdmse/common/coil/CoilExtensions.kt, app/src/main/java/eu/darken/sdmse/common/coil/CoilModule.kt, app/src/main/java/eu/darken/sdmse/common/coil/PathPreviewFetcher.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/ui/details/corpse/elements/CorpseElementFileVH.kt, app/src/main/java/eu/darken/sdmse/main/core/GeneralSettings.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/ui/details/filtercontent/elements/FilterContentElementFileVH.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_general.xml
File previews in all tools.
Can be disabled in settings.
Works for video and image types.
Supports access via Root and SAF.
Also see #314
=> File previews in all tools

app-common/src/main/java/eu/darken/sdmse/common/permissions/Permission.kt, app/src/main/AndroidManifest.xml, app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/common/SystemSettingsProvider.kt, app/src/main/java/eu/darken/sdmse/setup/SetupFragmentVM.kt, app/src/main/java/eu/darken/sdmse/setup/accessibility/AccessibilitySetupModule.kt
It can be pretty annoying if the system keeps killing the accessibility service and you are being asked on every other launch of SD Maid to enable it again (Chinese ROMs 👀).
This PR adds a hidden restart mechanism for power users:
If you grant SD Maid the `WRITE_SECURE_SETTINGS` permission via ADB, then SD Maid will use this to restart the service when necessary.
The documentation for this can be found here, in the ACS troubleshooting section:
https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-automatic-service-restart
=> Setup: Automatic ACS restart if extra permissions are available (via ADB)

app/src/main/java/eu/darken/sdmse/common/pkgs/InstalledPathAreaMapping.kt
Change `getPrivateDataDirs` to return empty instead of throwing an exception.
=> Fix regression: AppCleaner failing without root

app/src/main/java/eu/darken/sdmse/automation/core/AutomationManager.kt, app/src/main/java/eu/darken/sdmse/setup/SetupHealer.kt, app/src/main/java/eu/darken/sdmse/setup/SetupHelper.kt, app/src/main/java/eu/darken/sdmse/setup/SetupViewModel.kt, app/src/main/java/eu/darken/sdmse/setup/automation/AutomationSetupCardVH.kt, app/src/main/java/eu/darken/sdmse/setup/automation/AutomationSetupModule.kt, app/src/main/res/values/strings.xml
If SD Maid has access to Shizuku, or has been manually granted the `WRITE_SECURE_SETTINGS` permission, then SD Maid is able to self launch the accessibility service.
SD Maid will now detect this, and only launch the accessibility service for the duration of task. This is good for resource use, and also prevents the system from annoying the user with notifications about "SD Maid SE" being able to read the screen.
```
20:32:40.706 SDMSE:Automation:Manager             D  submit(): eu.darken.sdmse.appcleaner.core.automation.ClearCacheTask@df294a6
20:32:40.710 SDMSE:Automation:Manager:SR          D  Acquiring shared resource...
20:32:40.710 SDMSE:Automation:Manager             V  serviceLauncher.onStart()
20:32:40.710 SDMSE:Automation:Manager             D  serviceLauncher: …
```
=> AppCleaner: Launch accessibility service on demand if `WRITE_SECURE_SETTINGS` is available

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/storage/StorageEnvironment.kt
`LocalPath.exists()` returned wrong results for access mode=NORMAL on Android 12 for Android/data due to evaluating the fallback clause and thinking the storage root (e.g. `/storage/emulated/0` is a good indicator whether the `File.exists()` result is trust worthy. This just isn't the case anymore on Android 12+.
See https://github.com/d4rken-org/sdmaid-se/issues/315, potential fix.
=> IO: Fix `LocalPath.exists()` check on Android 12+ for Android/data.

app-common/src/main/java/eu/darken/sdmse/common/WebpageTool.kt
Some devices have no browser, but for some reason MXPlayer tries to open it and crashes.
=> Fix crash on device without browser when trying to open a website.

app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/PkgRepo.kt
Trying to track a background crash, still can't figure out what triggers it.
=> Leave a breadcrumb for debugging when package data has changed.

app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/ShizukuManager.kt, app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupCardVH.kt, app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
* Only allow "enable" to be clicked if Shizuku is installed
* Only show the link status if Shizuku is installed and enabled
* Don't disable the radio buttons when a permission is pending
* Don't try to access Shizuku service or binder if Shizuku is not installed or enabled
* Don't reset enabled state if Shizuku access is lost externally
=> Improve Shizuku setup

app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/PostProcessorModule.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/ui/details/corpse/CorpseFragment.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/ui/details/corpse/CorpseViewModel.kt, app/src/main/java/eu/darken/sdmse/exclusion/core/ExclusionExtensions.kt, app/src/main/java/eu/darken/sdmse/exclusion/core/types/PathExclusion.kt, app/src/main/java/eu/darken/sdmse/exclusion/core/types/PkgExclusion.kt, app/src/main/java/eu/darken/sdmse/exclusion/core/types/SegmentExclusion.kt, app/src/main/res/menu/menu_corpsefinder_corpse_cab.xml, app/src/test/java/eu/darken/sdmse/common/exclusion/core/ExclusionExtensionsTest.kt
Corpses that have content items are always folders.
If we create exclusions for content items, we must always exclude the top level item, i.e. the root corpse itself -> removing the whole entry.
So excluding a content item is always the same as excluding the whole corpse.
So to reduce confusion here, I removed the exclusion context option for content items.
=> CorpseFinder: Remove impossible exclusion actions for corpse content items

app/src/main/java/eu/darken/sdmse/appcleaner/core/deleter/AppJunkDeleter.kt
If the exists/lookup check fails, this can also be a ReadException. WriteException only comes from actual deletion failures, but we still need to look up all the files we want to delete.
=> AppCleaner: Fix abort on deletion error

app/src/main/java/eu/darken/sdmse/automation/core/AutomationManager.kt
If the service is already enabled, but not running, let's turn it off/on and see if that helps.
In response to a situation encountered in a log here: https://github.com/d4rken-org/sdmaid-se/issues/460#issuecomment-1637077942
=> Attempt to recover malfunctioning ACS if permissions allow it.

app-common/src/main/res/values/strings.xml, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt, app/src/main/res/layout/appcontrol_list_fragment.xml
* Restart filter operations (cancel previous ones) if filter options are changed rapidly.
* Add a "Clear filter" button.
* Hide refresh button is the filter pane is open.
* Add "inbetween" progress state for the UI operations
Closes #526
=> AppControl: Improve list filter interaction and behaviour

app/src/main/java/eu/darken/sdmse/common/areas/modules/DataAreaFactory.kt
Explicitly log areas if we have duplicate data and are throwing.
Got this from an automatic report, don't understand it. Need more logging if this happens again. Device infos look a bit sus though 👀 
```
brand realme
manufacturer SkyworthDigital
model 4K Google TV Stick
osVersion 11
runtimeVersions {
"androidApiLevel": "30",
"osBuild": "RTT0.210618.003.C1.0.1_20221203 release-keys"
}
```
```
java.lang.IllegalStateException: Duplicate data areas with overlapping paths
```
=> Improve debug logging

app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/watcher/ExternalWatcherResult.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/watcher/UninstallWatcherNotifications.kt
* Allow for more space to not cut off text.
* Display app name instead of packagename if available.
Closes #569
=> CorpseFinder: Improve uninstall watcher notifications

app-common-io/src/main/java/eu/darken/sdmse/common/storage/StorageEnvironment.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/SdcardsModule.kt
The "Kids Account" is returned via UserManager, but we can't find a specific data area for it and end up with duplicate Android/media data areas.
=> Android TV: Fix storage detection crashing

app/src/main/java/eu/darken/sdmse/corpsefinder/core/watcher/UninstallWatcherNotifications.kt
=> CorpseFinder: Fix uninstall watcher deletion not working correctly.

app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicDataModule.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicMediaModule.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicObbModule.kt
Some devices (Samsung @ A13…) can return "`canRead()` == true", but fail other operations. :roll_eyes:
=> Setup: Perform extra checks on Android/* during data area detection

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt
MIUI has two different system details screen, one that is like AOSP and one that is MIUI custom. SD Maid did only use AOSP API14+ labels for the first type, and did not automatically use newer labels on newer Android versions. I hope this does not break matching on some devices while fixing it on others...
Closes #627
=> AppCleaner: Fix ACS label lookup for MIUI on newer Android versions.

app-common-io/src/main/java/eu/darken/sdmse/common/ModeUnavailableException.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/ipc/PkgOpsHost.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppInfo.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/FilterSettings.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListRowVH.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionViewModel.kt, app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt, app/src/main/java/eu/darken/sdmse/setup/SetupModuleExtensions.kt, app/src/main/res/layout/appcontrol_list_fragment.xml, app/src/main/res/layout/appcontrol_list_item.xml, app/src/main/res/layout/appcontrol_tag_active_view.xml, app/src/main/res/values/strings.xml
=> AppControl: Show tags for recently active apps

app/src/main/java/eu/darken/sdmse/setup/SetupViewModel.kt, app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupCardVH.kt, app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt, app/src/main/res/values/strings.xml
This makes the behavior analog to the root setup card and also makes users that are not yet using Shizuku, aware of the option being possible.
Closes #641
=> Setup: Show Shizuku card even if Shizuku app is not detected

app-common/src/main/java/eu/darken/sdmse/common/AndroidModule.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/automation/core/ScreenState.kt
This fixes the issue that some users were not able to dismiss their lockscreen while the overlay was active, but they were also not able to dismiss the overlay.
=> AppCleaner: If the lock screen becomes active, hide the overlay until the lockscreen is dismissed

app-common/src/main/java/eu/darken/sdmse/common/ipc/BinderExtensions.kt
Closes #689
Full stacktrace was:
```java
E  getInterfaceFromBinder() failed: java.lang.NoSuchFieldException: No field DESCRIPTOR in class Leu/darken/sdmse/common/root/service/RootServiceConnection$Stub; (declaration of 'eu.darken.sdmse.common.root.service.RootServiceConnection$Stub' appears in /data/app/~~EMtqW8brkim4xhEVD5O_QA==/eu.darken.sdmse-DoVHI6JXBh7_Q7fsel3LcA==/base.apk!classes12.dex)
at java.lang.Class.getDeclaredField(Native Method)
at eu.darken.sdmse.common.ipc.BinderExtensionsKt.getInterface(BinderExtensions.kt:18)
at eu.darken.sdmse.common.root.service.internal.RootHostLauncher$createConnection$1$ipcReceiver$1.onConnect(RootHostLauncher.kt:57)
at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.doOnConnect(RootConnectionReceiver.kt:164)
at …
```
=> Root/Shizuku: Fix not being able to bind the service interface after AGP updating AGP 8.0.2->8.1.2

app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/SAFGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/SAFPathExtensions.kt, app/src/main/java/eu/darken/sdmse/setup/saf/SAFSetupModule.kt
Google seems to have backported some Android 14 changes with tighter restrictions on access to `Android/data` and `Android/obb` The previous `EXTRA_INITIAL_URI` argument trick is no longer working.
Also see:
https://cs.android.com/android/platform/superproject/main/+/main:packages/apps/DocumentsUI/src/com/android/documentsui/picker/ActionHandler.java;l=84;bpv=1;bpt=0;drc=901f1d6044aade190bb943ccc18d26244132648e;dlc=306a2b606a1f01498d2d83a1d8362962f114e6e8
There are now 3 states to this for Android 11 and Android 12 users:
* You have the original "Files" app (API-level 31, e.g. `aml_doc_310851020 (310851020)`) that came with your ROM, then you can just grant access as expected
* You have the latest "Files" app (API-level 34 or later, e.g. `14-10492947 (340916000)`), then you can't grant …
=> Setup: Improve SAF access handling on Android 11 and Android 12 after Google Play system update of the `Files` app

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/automation/core/ScreenState.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/PlanAbortException.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/ScreenUnavailableException.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/StepProcessor.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/AutomationExplorer.kt, app/src/main/res/values/strings.xml
Operations that use the accessibility service may obstruct the user. In some cases the lockscreen prevented the user from canceling. So #685 disabled the overlay if the screen is unavailable, e.g. the lockscreen is active.
This change goes a step further.
The overlay is still hidden if the screen becomes unavailable, but we will also throw a special Exception that should propagate up the stack and cancel the whole operation.
So to stop the automation, turning off the screen is enough. The automation itself keeps the screen from timing-out, so this should only happen if the user manually presses the power button.
Also see #692.
Closes #686
A "pause" option would be inappropriate here, screen becoming unavailable is an exceptional state.
=> Automation: Cancel automation if the screen becomes unavailable

buildSrc/src/main/java/ProjectConfig.kt
**Fix:** ``targetSdk: Int?' is deprecated. Will be removed from library DSL in v9.0``
**Reference:** https://stackoverflow.com/questions/75256272/kotlin-multiplatform-mobile-targetsdk-deprecated
=> targetSdk: Int? is deprecated

app/src/main/java/eu/darken/sdmse/setup/SetupModuleExtensions.kt
If the user clicks a setting that requires further setup, and then navigates back one level before clicking "Set up", then we crash. Not sure how common this is IRL, but Google's monkey testing runs into this regularly.
=> UI: Fix crash when going to setup from a settings "setup required" hint

app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCrawler.kt
SD Maid should skip `Android/data`, `Android/obb` and `Android/media` when scanning the `SDCARD` area as they will be scanned in an additional step if available. This skipping did not work correctly because it was based on `currentAreas` which would not contain, e.g. `PUBLIC_DATA` aka `Android/data` was not accessible and not setup as detected area.
=> SystemCleaner: Prevent early abort due to reading inaccessible paths

app/src/gplay/java/eu/darken/sdmse/common/upgrade/core/UpgradeRepoGplay.kt, app/src/gplay/java/eu/darken/sdmse/common/upgrade/core/billing/client/BillingConnection.kt
Previously we used `orderId` to check for valid purchases but apparently this is not a reliable way to check state.
While [documentation](https://developer.android.com/reference/com/android/billingclient/api/Purchase#getOrderId()) says:
> The order ID will be null if the purchase is in the Purchase.PurchaseState.PENDING state and populated if the purchase has transitioned to the Purchase.PurchaseState.PURCHASED state.
in reality I could reproduce cases where the `orderId` field was `null` despite `getPurchaseState() == PURCHASED`. What up Google?
My best guess so far is that the cached data that `queryPurchasesAsync` sometimes returns, does not always contain all fields. Clearing Google Play cache can reset it and fix that, but it's unclear why and when the "half-cached" state returns.
A …
=> Google Play: Improve upgrade check reliability

app-common/src/main/java/eu/darken/sdmse/common/TimeExtensions.kt, app/src/main/java/eu/darken/sdmse/scheduler/core/Schedule.kt, app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerManager.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/SchedulerDashCardVH.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/items/ScheduleRowVH.kt, app/src/test/java/eu/darken/sdmse/scheduler/core/ScheduleTest.kt
Check if the schedule has executed prematurely and prevent immediate re-execution. Also refactoring and some tests.
Possible fix for #692
=> Scheduler: Improve time calculation

app-common/src/main/java/eu/darken/sdmse/common/BuildWrap.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppAsecFileCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppLibCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppSourceCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppSourcePrivateCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/DalvikCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/PrivateDataCorpseFilter.kt
i.e. before letting these loose on Android 15/16, we should test them. Theoretically this is an issue with all tools, but the CorpseFinder would have the most negative impact on unsuspecting users.
=> CorpseFinder: Disable root based filters on unknown API levels

app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt
Displayed name should stay the same, but let's trim it when sorting and creating the scroll legend.
=> AppControl: Trim app names before handling (trim whitespace)

app/src/main/java/eu/darken/sdmse/deduplicator/ui/PreviewDeletionDialog.kt, app/src/main/java/eu/darken/sdmse/deduplicator/ui/details/cluster/elements/PHashGroupFileVH.kt, app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListGridVH.kt, app/src/main/res/layout/deduplicator_cluster_element_phashgroup_file.xml, app/src/main/res/layout/view_delete_confirmation_preview_grid_item.xml, app/src/main/res/layout/view_delete_confirmation_preview_single.xml
Use Coil's transformations to get rounded corners. Using Coil to load hardware supported bitmaps into `ShapeableImageView` can lead to crashs.
```
Exception java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode (BaseCanvas.java:749)
at android.graphics.BaseCanvas.throwIfCannotDraw (BaseCanvas.java:94)
at android.graphics.BaseCanvas.drawBitmap (BaseCanvas.java:152)
at android.graphics.Canvas.drawBitmap (Canvas.java:1604)
at android.graphics.drawable.BitmapDrawable.draw (BitmapDrawable.java:560)
at android.widget.ImageView.onDraw (ImageView.java:1446)
at com.google.android.material.imageview.ShapeableImageView.onDraw (ShapeableImageView.java)
```
Seems to happen randomly, this was:
```
samsung b0q …
```
=> Deduplicator: Fix crash when loading previews

app-common-io/src/main/java/eu/darken/sdmse/common/root/RootManager.kt, app/src/main/java/eu/darken/sdmse/setup/SetupViewModel.kt, app/src/main/java/eu/darken/sdmse/setup/root/RootSetupCardVH.kt, app/src/main/java/eu/darken/sdmse/setup/root/RootSetupModule.kt, app/src/main/res/layout/setup_root_item.xml, app/src/main/res/values/strings.xml
* Display a "root link state" similar to what we have for Shizuku
* If Magisk is detected, and the user has not made a yes/no decision about root, put the root setup card at the top as granting root, will automatically finish most other setup steps.
=> Setup: Improve root setup display and interaction

app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/DownloadCacheFilter.kt, app/src/test/java/eu/darken/sdmse/systemcleaner/core/filter/stock/DownloadCacheFiltertest.kt
Specifically to prevent deletion of `/cache/magisk/zygisk_lsposed/sepolicy.rule` etc.
Fixes #669
=> SystemCleaner: Exclude `/cache/magisk/zygisk_lsposed` from DownloadCache filter

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt
`canNormalWrite` also returns `false` if the file is deleted, then we aborted early with an exception. Instead we want to run into the `exists()` check later on and not throw an exception if the file no longer exists. This worked for ROOT and ADB, but not NORMAL due to the extra writable check
=> IO: Fix WriteException for already deleted files in NORMAL mode

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalPath.kt, app-common-io/src/test/java/eu/darken/sdmse/common/files/local/LocalPathTest.kt
`segmentsCache` is an internal performance improvement and should not be stored when serializing a `LocalPath`
=> IO: Fix LocalPath serializing transient fields for already deleted files in NORMAL mode

app-common/src/main/java/eu/darken/sdmse/common/DeviceDetective.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/SpecRomType.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/honor/HonorLabels.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/honor/HonorSpecs.kt
Currently AppCleaner treats HONOR devices/ROMs as ASOP ROMs and uses the matching there.
I've got one report now that could indicate that this no longer works with Android 13+ and that we might need special handling for the ROM.
=> AppCleaner: Support for HONOR devices with Android 13+

app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/StorageContentFragment.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/storage/StorageContentViewModel.kt
Decouple the long storage scans from the view model lifecycle and make it a background operation so the scan continues if the user put SD Maid in the background.
See https://github.com/d4rken-org/sdmaid-se/issues/876#issuecomment-1894806587
=> Analyzer: Keep scanning when app is in the background

app/src/gplay/java/eu/darken/sdmse/common/upgrade/core/UpgradeRepoGplay.kt, app/src/gplay/java/eu/darken/sdmse/common/upgrade/ui/UpgradeEvents.kt, app/src/gplay/java/eu/darken/sdmse/common/upgrade/ui/UpgradeFragment.kt, app/src/gplay/java/eu/darken/sdmse/common/upgrade/ui/UpgradeViewModel.kt, app/src/gplay/res/layout/upgrade_fragment.xml, app/src/gplay/res/values/strings.xml
Triggers a purchase data refresh and if that fails shows a few hints for common issues.
=> Google Play: Add extra "Restore purchase" button

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsHost.kt, app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/checksum/ChecksumSleuth.kt
=> Deduplicator: Improve error handling and skip unreadable files

app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/PkgRepo.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControlScanTask.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt
=> AppControl: Long pressing refresh force reloads the pkg cache

app/src/gplay/java/eu/darken/sdmse/common/upgrade/core/UpgradeRepoGplay.kt, app/src/testGplay/java/eu/darken/sdmse/common/upgrade/core/UpgradeRepoGplayTest.kt
Fix incorrect mapping of purchases to upgrade status due to mistake/regression from debugging.
Fix #959
=> Google Play: Fix upgrade status being ignored

app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerWorker.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerManagerViewModel.kt, app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
Previously if SD Maid was first setup for Shizuku, and then Shizuku is launched without restarting SD Maid, then you'd have to toggle Shizuku on/off in SD Maid again for SD Maid to ask for access to Shizuku.
=> Setup: Monitor Shizuku state and automatically request missing permission

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicDataModule.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicMediaModule.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/PublicObbModule.kt
Potential fix for
```java
2024-02-04T12:34:53.242Z  I/SDMSE:Debug:Log:Recorder:Module: APILEVEL: 34
2024-02-04T12:34:53.242Z  I/SDMSE:Debug:Log:Recorder:Module: Build.FINGERPRINT: samsung/dm2qxeea/dm2q:14/UP1A.231005.007/S916BXXS3BWL3:user/release-keys
2024-02-04T12:34:53.242Z  I/SDMSE:Debug:Log:Recorder:Module: Build.MANUFACTOR: samsung
2024-02-04T12:34:53.242Z  I/SDMSE:Debug:Log:Recorder:Module: Build.BRAND: samsung
2024-02-04T12:34:53.242Z  I/SDMSE:Debug:Log:Recorder:Module: Build.PRODUCT: dm2qxeea
2024-02-04T12:34:53.242Z  I/SDMSE:Debug:Log:Recorder:Module: App: eu.darken.sdmse - 0.19.1-beta0 (1901000) 
2024-02-04T12:34:53.242Z  I/SDMSE:Debug:Log:Recorder:Module: Build: GPLAY-BETA
2024-02-04T12:34:53.244Z  I/SDMSE:Debug:Log:Recorder:Module: App locales: [de_DE] …
```
=> IO: When detecting available data areas, perform a `listFiles` in addition to `lookup` to check access

app-common-io/src/main/aidl/eu/darken/sdmse/common/files/local/ipc/FileOpsConnection.aidl, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathLookupExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/GatewaySwitch.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/PathTreeFlow.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/PathWalker.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/DirectLocalWalker.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/EscalatingWalker.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/IndirectLocalWalker.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/SAFGateway.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt, app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/SdcardCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/checksum/ChecksumSleuth.kt, app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/phash/PHashSleuth.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCrawler.kt
Less back and forth between SD Maid and root/shizuku processes when traversing nested directories. If we handle all the traversing on one side (in one process) then we don't have to proxy extra calls for each directory through the IPC buffer. 🥳 
TODO: Some of the access type mechanisms fail when with this optimisation, i.e. tries NORMAL, but not ADB when in `Mode.AUTO` 🤔
=> IO: Improve scan performance with Root & Shizuku

app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/common/InjectionHelpers.kt
Check if we are launched by a 3rd party and if we are, don't init and abort early. Crashing repeatedly could block the ACS from being launched until reboot. This can happen if the app is launched in a `restricted` mode by the system.
e.g.
```java
Exception java.lang.RuntimeException:
at android.app.ActivityThread.handleCreateService (ActivityThread.java:4681)
at android.app.ActivityThread.access$100 (ActivityThread.java:255)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2204)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loopOnce (Looper.java:238)
at android.os.Looper.loop (Looper.java:349)
at android.app.ActivityThread.main (ActivityThread.java:8262)
at java.lang.reflect.Method.invoke
at …
```
=> ACS: Prevent platform bug that can cause ACS to crash and deactivate

app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/DocumentFileExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/SAFDocFile.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/features/Installed.kt, app-common/src/main/res/values/strings.xml, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppInfo.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/export/AppExportTask.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/export/AppExportType.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/export/AppExporter.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/toggle/ComponentToggler.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListEvents.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListRowVH.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionAdapter.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionDialog.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionEvents.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionViewModel.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/items/ExportActionVH.kt, app/src/main/java/eu/darken/sdmse/common/MimeTypeTool.kt, app/src/main/java/eu/darken/sdmse/common/MimeTypes.kt, app/src/main/res/layout/appcontrol_action_backup_item.xml, app/src/main/res/layout/appcontrol_action_dialog.xml, app/src/main/res/layout/appcontrol_list_item.xml, app/src/main/res/layout/appcontrol_tag_apk_base_view.xml, app/src/main/res/layout/appcontrol_tag_apk_bundle_view.xml, app/src/main/res/menu/menu_appcontrol_list_cab.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Closes #664
Examples:
```bash
r8q:/sdcard/exporttest $ ls -l
total 31224
-rw-rw---- 1 root everybody 26804541 2024-02-22 17:14 YouTube\ Music\ (com.google.android.apps.youtube.music)\ -\ 6.37.50[63750240].apks
-rw-rw---- 1 root everybody  5131806 2024-02-22 17:14 ZArchiver\ (ru.zdevs.zarchiver)\ -\ 1.0.9[10925].apk
```
`.apks` bundles are installable by common apps like ZArchiver, XAPKs Installer or APK Mirror Installer.
=> AppControl: Add feature that allows exporting APKs and split APKs

app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/PkgRepo.kt, app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/sources/PackageManagerPkgSource.kt, app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/sources/QueryAllPkgsPermissionMissing.kt, app-common/src/main/java/eu/darken/sdmse/common/permissions/Permission.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/Analyzer.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScanner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/settings/AppCleanerSettingsFragment.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/ui/settings/CorpseFinderSettingsFragment.kt, app/src/main/java/eu/darken/sdmse/setup/IncompleteSetupException.kt, app/src/main/java/eu/darken/sdmse/setup/SetupAdapter.kt, app/src/main/java/eu/darken/sdmse/setup/SetupModule.kt, app/src/main/java/eu/darken/sdmse/setup/SetupModuleExtensions.kt, app/src/main/java/eu/darken/sdmse/setup/SetupScreenOptions.kt, app/src/main/java/eu/darken/sdmse/setup/SetupViewModel.kt, app/src/main/java/eu/darken/sdmse/setup/inventory/InventorySetupCardVH.kt, app/src/main/java/eu/darken/sdmse/setup/inventory/InventorySetupModule.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/ui/settings/SystemCleanerSettingsFragment.kt, app/src/main/res/layout/setup_inventory_item.xml, app/src/main/res/values/strings.xml
Previous we always assumed that QUERY_ALL_PACKAGES was granted (which it should, by default), but Samsung seems to be doing "Just Samsung things :tm:" and this may not be the case on some of Samsungs Android 14 ROMs. So let's treat it as potentially optional and catch the error, don't crash, and guide the user to the setup.
Closes #1015
=> Setup: Gracefully handle QUERY_ALL_PACKAGES permission being optional on some devices

app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/sources/PackageManagerPkgSource.kt
Previously we only did this if root is available, but we should be able to get the same data without root and Shizuku.
=> Core: Use Shizuku to query for additional installed apps

app/src/main/assets/clutter/db_clutter_markers.json, app/src/main/assets/expendables/db_trash_files.json, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/AdvertisementFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/BugReportingFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/CodeCacheFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/GameFilesFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/HiddenFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/RecycleBinsFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ThumbnailsFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt, app/src/main/java/eu/darken/sdmse/common/clutter/dynamic/NestedPackageMatcher.kt, app/src/main/java/eu/darken/sdmse/common/clutter/dynamic/modules/SamsungTrashDynamicMarker.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/LinuxFilesFilter.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/AdvertisementFilterTest.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/BugReportingFilterTest.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/RecycleBinsFilterTest.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ThumbnailsFilterTest.kt, app/src/test/java/eu/darken/sdmse/common/clutter/dynamic/modules/SamsungTrashDynamicMarkerTest.kt, app/src/test/java/eu/darken/sdmse/systemcleaner/core/filter/stock/LinuxFoldersFilterTest.kt
Prevent SystemCleaner's "Linux Files" filter from picking up the default trash folder on Samsung devices.
Support app specific matching of files in the system's recycle bin folder on Samsung devices
e.g.:
`/sdcard/Android/.Trash/<gallery/myfiles etc.>/<trash files>`
Closes https://github.com/d4rken-org/sdmaid-se/issues/1057
=> AppCleaner: Improve recycle-bin filter on Samsung devices

app/src/main/java/eu/darken/sdmse/common/locale/LocaleExtensions.kt, app/src/main/java/eu/darken/sdmse/common/locale/LocaleManager.kt, app/src/main/java/eu/darken/sdmse/main/core/motd/MotdRepo.kt, app/src/main/java/eu/darken/sdmse/main/ui/settings/general/GeneralSettingsFragment.kt, app/src/main/java/eu/darken/sdmse/main/ui/settings/general/GeneralSettingsViewModel.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_general.xml
Shows the current language and opens the system's app specific language picker. Only available on Android 13+ as this uses a new system API.
Closes #1046
Also see #991
=> UI: Add setting to open language changer on Android 13

app/src/main/res/layout/dashboard_title_item.xml, buildSrc/src/main/java/Dependencies.kt, buildSrc/src/main/java/ProjectConfig.kt
Was an attempt at fixing:
https://github.com/material-components/material-components-android/issues/4101
Not fixed, but let's keep the updated dependencies.
=> General: Bump material-components version and targetSDK to 34

app/src/main/java/eu/darken/sdmse/analyzer/core/storage/AppStorageScanner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLabler.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/alcatel/AlcatelSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/coloros/ColorOSSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/flyme/FlymeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/honor/HonorSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/huawei/HuaweiSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/lge/LGESpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/nubia/NubiaSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oneplus/OnePlusSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/realme/RealmeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/samsung/SamsungSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/vivo/VivoSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/InaccessibleCacheProvider.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AccessibilityNodeExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt, app/src/main/java/eu/darken/sdmse/common/storage/StorageStatsManager2.kt
Most "Storage" entries in system details have a summary row that says something like "604 MB in internal storage" While we don't know the translation of "in internal storage", we know the app size, so we can look for "604 MB". There is a slight chance for false-positives if the data-usage of the app is the same as the app size, but that's pretty rare. If that happens SD Maid just keeps retrying as usual.
With 218 apps this had a 99% success rate.
There was one app ("Digital Wellbeing", a system app), that showed the wrong app size (36,06 MB) on first load. Only when SD Maid retried and reloaded the settings details, the size displayed correct (35,96 MB). No idea why the size was displayed incorrectly the first time...
When clearing caches via ACS we now have 3 tier process:
1. Try to get …
=> AppCleaner: Improve ACS based cache clearing resilience by detecting storage entries "on-the-fly" via app size values

app/src/main/java/eu/darken/sdmse/common/areas/modules/misc/PortableModule.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/pub/SdcardsModule.kt
Dropping the old legacy code from SD Maid 1 here, partly still stuff from Android 2.1.
Adopt the newer approach based on `StorageManager`, similar to SDCARD detection, but we filter out any covered path and try to get the `isUSB` flag via reflection.
This makes detection of a USB sticks work in my Samsung Tab A9+ (Android 14).
=> Core: Improve portable storage detection (e.g. USB Stick in Tablet)

app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootConnectionReceiver.kt
Missing receiver flags about export status.
Tested with Magisk 27.0 but should also fix it for KernelSU
Fixes #1073
Fixes #1069
=> Root: Fix root service connection crashing on Android 14

app/src/main/AndroidManifest.xml, app/src/main/java/eu/darken/sdmse/common/debug/recorder/core/RecorderService.kt
Also add a safeguard that automatically stops the log again if the service crashes.
=> Debug: Fix debug log causing crash loop on Android 14

app/src/main/java/eu/darken/sdmse/analyzer/core/storage/AppStorageScanner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/InaccessibleCacheProvider.kt
`queryStatsForAppUid` can include data sizes from other apps if they share the same user-id (common among system apps). We want "per package" i.e. `queryStatsForPkg`.
Fixes #818
=> AppCleaner/StorageAnalyzer: Fix cache size calculation for apps with shared user ids

app/src/main/java/eu/darken/sdmse/appcleaner/core/InaccessibleDeleter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/InaccessibleDeletionException.kt, app/src/main/res/layout/dashboard_title_item.xml
Previously all setup items were shown instead of just the required one, and it would kick you back to the dashboard instead of the page where the error dialog was popped.
=> AppCleaner: Improve setup behavior when ACS is not enabled but required

app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/tasks/AppCleanerOneClickTask.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/tasks/CorpseFinderOneClickTask.kt, app/src/main/java/eu/darken/sdmse/deduplicator/core/Deduplicator.kt, app/src/main/java/eu/darken/sdmse/deduplicator/core/tasks/DeduplicatorOneClickTask.kt, app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCleaner.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/tasks/SystemCleanerOneClickTask.kt
One-Tap-Mode was tied to the viewmodel lifecycle and a combination of the default scan-task and delete-task, if the viewmodel gets collected (e.g. due to ACS opening system settings over SD Maids main UI, than the coroutine that would have launched the follow up deletion task, is cancelled. The scan task still continues because after a task is launched, it is tied to the global app scope.
So let's fix this by just creating a special One-Click-Task that will internally perform scan + delete.
=> Dashboard: Fix One-Tap-Mode sometimes not executing deletion task

app/src/main/java/eu/darken/sdmse/setup/shizuku/ShizukuSetupModule.kt
If we hang at the Shizuku check (most likely during service binding), then timeout after 6 seconds and assume `useShizuku=null`. `null` so the setup is shown again in any case.
6 seconds seems long but this is an edge-case normally it should respond with either success or failure, can't identify why it sometimes gets stuck, doesn't seem to be caused by SD Maid though.
Closes #1079
=> Shizuku: Don't hang on dashboard if Shizuku is not responding

app/build.gradle.kts
See https://github.com/6eero/NewPass/issues/1#issuecomment-2021340229
Randomly stumbled upon the above issue and think this is worthwhile to do too.
@IzzySoft I could swear that you raised this topic for SD Maid SE too, but I can't find anything. Deja vu...? :thinking:
=> FOSS: Remove Google's encrypted DEPENDENCY_INFO_BLOCK from FOSS builds

app/src/main/java/eu/darken/sdmse/exclusion/core/ExclusionManager.kt
We access `val current = exclusions.first()` a lot which would previously do the data merge (user+defaults) every time, that's wasted performance, let's do it once and keep it in memory.
This increases RAM usage, but as exclusions are used in all tools anyways, it shouldn't matter.
Might be cool though to make exclusions a `SharedResource` in the future to scope it better, like other modules (e.g. `FileForensics`).
=> Exclusions: Improve filter performance by keeping exclusion data loaded

app/src/main/java/eu/darken/sdmse/automation/core/AutomationManager.kt, app/src/main/java/eu/darken/sdmse/setup/automation/AutomationSetupModule.kt
In addition to checking if it is running, we need to also check if we could launch it.
=> Automation: Fix accessibility service unavailable error even though it could be self-launched

app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/phash/PHashSleuth.kt, app/src/main/java/eu/darken/sdmse/exclusion/core/DefaultExclusions.kt, app/src/main/java/eu/darken/sdmse/exclusion/core/ExclusionManager.kt
No user-visible impact but wasn't stored the way it was intended.
User exclusions were added to the "removed default exclusions" data set.
Unrelated but noticed when checking logs from https://github.com/d4rken-org/sdmaid-se/issues/1135
=> Exclusions: Fix internally mixing up user exclusions and default exclusions

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/androidtv/AndroidTVLabels.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/coloros/ColorOSLabels.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/flyme/FlymeLabels.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/flyme/FlymeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUILabels.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/realme/RealmeSpecs.kt
Fix accessibility based cache clearing aborting with an error because extra language labels could not be looked up even tough we had at least one label we could work with.
Static lookups can be empty can be empty, we still might have labels from dynamic lookups or can even match via onthefly lookups.
=> AppCleaner: Fix ACS label lookup on OPPO and Android TV devices

app/src/foss/java/eu/darken/sdmse/common/updater/FossUpdateChecker.kt, app/src/foss/java/eu/darken/sdmse/common/updater/GithubReleaseCheck.kt, app/src/foss/res/values-de/strings.xml, app/src/foss/res/values/strings.xml, app/src/gplay/java/eu/darken/sdmse/common/updater/GplayUpdateChecker.kt, app/src/gplay/res/values-de/strings.xml, app/src/gplay/res/values/strings.xml, app/src/main/java/eu/darken/sdmse/common/updater/UpdateChecker.kt, app/src/main/java/eu/darken/sdmse/common/updater/UpdateService.kt, app/src/main/java/eu/darken/sdmse/common/updater/UpdaterExtensions.kt, app/src/main/java/eu/darken/sdmse/main/core/CurriculumVitae.kt, app/src/main/java/eu/darken/sdmse/main/core/release/ReleaseManager.kt, app/src/main/java/eu/darken/sdmse/main/core/release/ReleaseSettings.kt, app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt, app/src/main/java/eu/darken/sdmse/main/ui/release/BetaGoodbyeFragment.kt, app/src/main/java/eu/darken/sdmse/main/ui/release/BetaGoodbyeViewModel.kt, app/src/main/res/layout/beta_goodbye_fragment.xml, app/src/main/res/navigation/main_nav.xml, app/src/main/res/values/strings.xml
When SD Maid goes from <1.0.0 to >= 1.0.0 we display a little release party screen.
The screen indicates that non-prereleases are available and helps the user switch to the release track.
For FOSS builds this means internally using the PROD instead of BETA channel for SD Maids updater.
For GPLAY builds it opens the testing opt-out page: https://play.google.com/apps/testing/eu.darken.sdmse
We also save whether the user has had any pre 1.0.0 versions installed to mark them as early adopter.
Later on we use this flag to ask for a re-review of SD Maid as any rating given during testing is not publicly displayed.
[Screenshot_20240425_153551](https://github.com/d4rken-org/sdmaid-se/assets/1439229/9f637c66-701a-40c6-b6cd-70d1b4b3a5cc)
[Screenshot_20240425_153514](https://github.com/d4rken-org/sdm …
=> Implement release party screen

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt
This usually happens if temporary files are deleted by their owner (or the system) before SD Maid can act on them.
We want to silently treat this as success.
This failed loudly though because `canWrite` returns false on a file that does not exist, so SD Maid thought no matching access mode was available.
A simple `exists()` check here is insufficient as we can't use that to differentiate between a file that does not exist, and us lacking the permission to determine if it exists.
=> IO: Fix WriteException when trying to delete files that don't exist

app-common/src/main/java/eu/darken/sdmse/common/device/DeviceDetective.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/LabelDebugger.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/AppControlAutomation.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationHost.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AccessibilityNodeExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationException.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/StepProcessor.kt, app/src/main/java/eu/darken/sdmse/automation/core/debug/DebugTaskModule.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/AutomationException.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/DisabledTargetException.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/PlanAbortException.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/ScreenUnavailableException.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/StepAbortException.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/AutomationExplorer.kt, app/src/main/res/xml/accessibility_service.xml
Stop using the root from accessibility events as fallback if `rootInActiveWindow` is null.
Delayed event emission can leave us with an out-dated (and later recycled) root node being used by the `StepProcessor`.
Error behavior:
* Click event (e.g. clear cache being clicked) from app 1 is emitted when SD Maid starts processing app 2
* windowRoot of app 2 is not ready yet
* SD Maid starts using fallback root from the last event (the click event from app 2)
* The fallback root is no longer valid, as it corresponds to the settings screen from app 1
* SD Maids keeps retrying and the fallback root is at some point recycled
* SD Maid keeps trying to crawl an empty root
Fixes https://github.com/d4rken-org/sdmaid-se/issues/1124
Might fix https://github.com/d4rken-org/sdmaid-se/issues/1016
=> Automation: Improve reliability one Android 14 devices (OnePlus & Redmi)

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/AppControlAutomation.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt
Instead of back-button presses (i.e. `GLOBAL_ACTION_BACK`) that don't work reliably on Android 14 anymore, we use intent navigation to return to SD Maid at the end. So far, this proved reliable on API29, API31 and API34. Opening the system settings activity was quick, and returning to SD Maid was quick too. No extra activity remained in the task-switcher.
=> Automation: Better return behaviour after accessibility operations

app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/InaccessibleDeleter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheTask.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/tasks/AppCleanerProcessingTask.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationExtensions.kt
If automation is used from the background (scheduler or a future widget), don't return to the main app after operations are finished. Previously this was also the case, but due to going back by "back button", it wasn't that visible.
=> AppCleaner: Don't return to app when using accessibility functions via scheduler

app-common-io/src/main/java/eu/darken/sdmse/common/files/GatewaySwitch.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/storage/AppStorageScanner.kt
Shouldn't happen, but if it happens, we have some fallbacks to turn to.
See #1173
=> Analyzer: Improve error handling when file paths can't be read despite escalated privileges

app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionDialog.kt
From a
>  samsung a05m (Galaxy A05)
>  Android 14 (SDK 34)
e.g.
```
Exception android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
at android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:2252)
at android.app.Instrumentation.execStartActivity (Instrumentation.java:1878)
at android.app.Activity.startActivityForResult (Activity.java:5743)
at androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:2)
at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult
at androidx.activity.ComponentActivity$1.onLaunch (ComponentActivity.java)
at androidx.activity.result.ActivityResultLauncher.launch (ActivityResultLauncher.java:132)
at …
```
=> AppControl: Fix crash when trying to export app and the phone's files picker is unavailable

app-common-io/src/main/aidl/eu/darken/sdmse/common/files/local/ipc/FileOpsConnection.aidl, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathLookupExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/GatewaySwitch.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/EscalatingWalker.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalPathExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/SAFGateway.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/Analyzer.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/storage/AppDeepScanTask.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/storage/AppStorageScanner.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScanner.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScannerExtensions.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/storage/categories/AppCategory.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/app/AppDetailsViewModel.kt
Defer scanning apps in details until the user actually needs it. During the first pass of all apps, we only do a "shallow" scan, and then only if the enters the app details, then we do a deep scan.
The "shallow" scan uses the systems app storage stats as base information, actually scanning the files of each then only happens on demand.
This is a little less accurate, but a lot faster, and worth the trade off imho.
=> Analyzer: Speed up scans

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/AppControlAutomation.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationExtensions.kt
When finishing automation actions and we launched from the background (e.g. via Scheduler), then don't open SD Maid. If we don't open SD Maid, then call the "HOME" button, so that the last opened app settings screen is not visible.
Fixes #1213
=> Scheduler: Close last opened app by going to the home screen

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/PackageManagerExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/ipc/PkgOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/ipc/PkgOpsHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shell/ipc/ShellOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shell/ipc/ShellOpsHost.kt, app-common/src/main/java/eu/darken/sdmse/common/ipc/IpcClientModule.kt, app-common/src/main/java/eu/darken/sdmse/common/ipc/IpcHostModule.kt
#1233 and #1234 would have been easier to debug with this.
It's not as good as I hoped for because the stacktrace doesn't propagate through the binder correctly. Serializing the trace into the exception message is hackyasf but I didn't find a better solution. If anyone finds a better way :beers: are on me. This is only used if `isDebug==true` so I think we can live with the hacky solution.
=> Refactor Client/Host cross process exception propagation

app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt
Via playconsole
```
Exception java.util.NoSuchElementException: List is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.single (CollectionsKt___Collections.kt:2)
at eu.darken.sdmse.appcontrol.ui.list.AppControlListFragment$onViewCreated$$inlined$observe2$2.invoke (AppControlListFragment.java)
at eu.darken.sdmse.appcontrol.ui.list.AppControlListFragment$onViewCreated$$inlined$observe2$2.invoke (AppControlListFragment.java)
at androidx.lifecycle.LiveData.considerNotify (LiveData.java)
at androidx.lifecycle.LiveData.dispatchingValue (LiveData.java)
at androidx.lifecycle.MutableLiveData.setValue (MutableLiveData.java)
at eu.darken.sdmse.common.SingleLiveEvent.setValue (SingleLiveEvent.java)
at androidx.lifecycle.LiveData$1.run
at android.os.Handler.handleCallback (Handler.java:938) …
```
=> AppControl: Fix crash when passing 0 selected items from multi selection

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/DirectLocalWalker.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/EscalatingWalker.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/IndirectLocalWalker.kt, app-common/src/main/java/eu/darken/sdmse/common/ipc/IpcClientModule.kt
The remote exception may fail to unwrap and then not be of subtype `IOException` and so would not be caught.
=> SystemCleaner: Fix scan aborting on error instead of gracefully continuing the search

app-common/src/main/java/eu/darken/sdmse/common/BatteryHelper.kt, app-common/src/main/java/eu/darken/sdmse/common/permissions/Permission.kt, app-common/src/main/res/values/strings.xml, app/src/main/AndroidManifest.xml, app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerSettings.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerAdapter.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerManagerEvents.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerManagerFragment.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerManagerViewModel.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/items/BatteryHintRowVH.kt, app/src/main/java/eu/darken/sdmse/setup/SetupViewModel.kt, app/src/main/res/drawable/ic_battery_heart_24.xml, app/src/main/res/drawable/ic_battery_lock_open_24.xml, app/src/main/res/layout/scheduler_manager_list_alarmhint_item.xml, app/src/main/res/layout/scheduler_manager_list_batteryhint_item.xml, app/src/main/res/values/strings.xml
Show a hint about disabling battery optimizations on newer Android versions where this may affect launching a foreground task, e.g. Android 14+.
I tested various API levels and starting with Android 12 (API31), we get an exception when starting foreground services while optimizations are enabled.
We didn't use `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` and shouldn't as black box Google Play is potentially allergic to it's use. Do the safe way of directing the user to the system settings.
Also see #1273 and #1247
```
14:15:39.704 SDMSE:Scheduler:Worker               D  Declaring as foreground task
14:15:39.704 SDMSE:Scheduler:Worker               D  Supplying getForegroundInfo() with Schedule(id=96b7c483-863d-4c9f-9baa-b5e1b6083ddc, createdAt=2024-07-05T12:14:14.886Z, …
```
=> Scheduler: Hint about battery optimizations

app/src/main/java/eu/darken/sdmse/stats/core/db/ReportsDatabase.kt, app/src/main/java/eu/darken/sdmse/stats/ui/settings/StatsSettingsFragment.kt, app/src/main/java/eu/darken/sdmse/stats/ui/settings/StatsSettingsViewModel.kt, app/src/main/res/xml/preferences_statistics.xml
Show item count and not database size.
Due to the database using -shm and -wal files, showing a size will confuse users trying to get it to "0KB". The previous checkpoint+deletion approach could cause crashes if the database was being accessed at that time.
=> Stats: Change reset UI and displayed info

app-common-io/consumer-rules.pro, app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootHostLauncher.kt, app-common-shizuku/src/main/java/eu/darken/sdmse/common/shizuku/service/internal/ShizukuHostLauncher.kt, app-common/src/main/java/eu/darken/sdmse/common/ipc/BinderExtensions.kt
After bumping dependencies and gradle/AGP in #1301 the proguard/R8 behavior changed and additional rules are now required.
Fixes #1305
Thanks @chaoscalm
=> Core: Fix proguard breaking Root and Shizuku service connections on release builds

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/AppControlAutomation.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationExtensions.kt
This restores the < v0.24.0 behavior of returning to SD Maid or the previous app by using the back button after automation (ACS) operations. Using the home button can interfere with Android TV launchers (see #1240).
Fixes #1240
=> AppCleaner: When using the scheduler on Android TV use back button in stead of home button after finishing ACS operations

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/vivo/VivoSpecs.kt
Vivo changed the target from a clickable text view:
```
14: className=android.widget.TextView, text=Clear cache, isClickable=true, isEnabled=true, viewIdResourceName=com.android.settings:id/button, pkgName=com.android.settings
```
to a nested textview with a clickable parent:
```
crawl():-----------11: className=android.widget.FrameLayout, text='null', isClickable=false, isEnabled=true, viewIdResourceName=null, pkgName=com.android.settings, identity=6ca774f
crawl():------------12: className=android.widget.LinearLayout, text='null', isClickable=false, isEnabled=true, viewIdResourceName=null, pkgName=com.android.settings, identity=e357d09
crawl():-------------13: className=android.widget.RelativeLayout, text='null', isClickable=false, isEnabled=true, viewIdResourceName=null, …
```
=> AppCleaner: Fix ACS automation not working on VIVO ROMs with Android 14

app/src/main/java/eu/darken/sdmse/main/core/taskmanager/TaskManager.kt, app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt, app/src/main/java/eu/darken/sdmse/scheduler/ui/manager/SchedulerManagerViewModel.kt
Improve how the task manager handles the task history. We pruned new tasks instead of old tasks.
As SD Maid uses the last task manager results to display either scan or deletion results, this lead to new scans not displaying their results in the dashboard.
=> Dashboard: Fix task results showing inconsistently

app/src/main/java/eu/darken/sdmse/exclusion/ui/editor/segment/SegmentExclusionFragment.kt, app/src/main/res/layout/exclusion_editor_segment_fragment.xml
Don't see a reason why this was not possible, seems like an oversight.
Noticed via #1331
=> Exclusions: Allow segment exclusions specific to SystemCleaner

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLabler.kt
Improve `OnTheFlyLabler` by also manually calculating the formatted size value. On a VIVO device with Android 14 (`vivo/PD2366/PD2366:14/UP1A.231005.007_MOD1/compiler07161632:user/release-keys`), the `formatFileSize` was the same as the `formatShortFileSize` despite the system showing a non "short" value.
The crawler showed that the storage entry looks like this
```
2024-07-30T08:08:44.858Z  V/SDMSE:Automation:Crawler: crawl():------------12: className=android.widget.TextView, text='Storage', isClickable=false, isEnabled=true, viewIdResourceName=com.android.settings:id/title, pkgName=com.android.settings, identity=6377116
2024-07-30T08:08:44.858Z  V/SDMSE:Automation:Crawler: crawl():------------12: className=android.widget.TextView, text='677,53 MB used in internal storage', …
```
=> AppCleaner: Improve dynamic storage entry label detection

app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt
Content deletion is the deletion of "sub items", i.e. files within a corpse itself, if the corpse is a directory. Usually you would delete the whole corpse though, anyways, the paths should be included in the results as otherwise result messages are wrong (0 items deleted) and statistics are incorrect.
=> CorpseFinder: Fix content deletion paths missing from results

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLabler.kt
Generate size variants with both `.` and `,` as decimal separator.
See #1344
=> AppCleaner: Improve dynamic label detection

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt
Fix services being destroyed before all data has been transferred Similar to `LocalGateway.read(...): Source` where we need to keep the source alive until consumed, we need to do the same when returning a `Flow`. It's up to the caller on when it's consumed.
Likely caused by #1345
Previously we had a constant lease on the Shizuku service resource so this never surfaced: https://github.com/d4rken-org/sdmaid-se/pull/1345/files#diff-3105723dbd44154e23041c05d9496670e61e15cbdcd00ea73c99d1984f577f76R135
Root will have the same issue as that changed in #1346
This fixes #1358
=> IO: Fix Root/Shizuku error when reading large directories

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootServiceClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootServiceClientExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/service/ShizukuServiceClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/service/ShizukuServiceClientExtensions.kt, app-common/src/main/java/eu/darken/sdmse/common/sharedresource/SharedResourceExtensions.kt, app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt
While the parent (LocalGateway or PkgOps) is active and they themself as resource are being kept alive, make sure we keep childs like Shizuku or Root sessions alive too. Closing and opening the service connections (releasing the child resources) while the parent resource is alive, just adds extra churn.
Also see #1360
```
18:46:35.645 SDMSE:TaskManager:SR                 D  get(205551414): Reviving SharedResource
18:46:35.650 SDMSE:TaskManager:SR                 D  Acquiring shared resource...
18:46:35.653 SDMSE:AppCleaner:SR                  D  get(163473936): Reviving SharedResource
18:46:35.656 SDMSE:AppCleaner:SR                  D  Acquiring shared resource...
18:46:35.664 SDMSE:CSI:FileForensics:SR           D  get(54980210): Reviving SharedResource
18:46:35.666 …
```
=> IO: Improve resource management during file operations

app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleanerExtensions.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/AppJunk.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/InaccessibleDeleter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/InaccessibleCache.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/InaccessibleCacheProvider.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/PostProcessorModule.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/elements/AppJunkElementInaccessibleVH.kt
The underlying issue is/was that without root we can't access "inaccessible caches", which are the default public and private caches of an app. The caches that get cleared when pressing the "Clear cache" button in the system.
If we throw Shizuku into the mix, then we can access the PUBLIC default caches, but not the private default caches.
So with Shizuku the inaccessible caches entry overlaps with the public default caches.
* When deleting the `Default caches` entry, then we also need to remove the `Public default caches` entry
* When deleting the `Public default caches` entry, then we need to subtract the size from the `Default caches` entry.
=> AppCleaner: Fix inconsistencies when using ACS and Shizuku

app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt
Was "count of apps with expendable files"
Now is the sum of matches across all apps and filters
=> AppCleaner: Fix found item count

app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/EmptyDirectoryFilter.kt, app/src/test/java/eu/darken/sdmse/systemcleaner/core/filter/SystemCleanerFilterTest.kt, app/src/test/java/eu/darken/sdmse/systemcleaner/core/filter/stock/EmptyDirectoryFilterTest.kt
=> SystemCleaner: Remove block/inode size limit when checking for empty directories

app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootServiceClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/service/ShizukuHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/service/ShizukuServiceClient.kt, app/src/main/java/eu/darken/sdmse/common/debug/recorder/ui/RecorderViewModel.kt
=> Fix Shizuku/Root logs not being included in debug logs

app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/BaseExpendablesFilter.kt
A file that we are trying to delete, may be un-readable in addition to being un-writable. So a `ReadException` could be thrown too.
While we can't fix the underlying issue that prevents a file from being read or written, we can continue on with the other deletion tasks, and just leave this one for the user to investigate.
Closes #1391
=> AppCleaner: If a file can't be accessed, continue with the other files

app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/BaseExpendablesFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/ExpendablesFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/AdvertisementFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/AnalyticsFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/BugReportingFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/CodeCacheFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/DefaultCachesPrivateFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/DefaultCachesPublicFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/GameFilesFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/HiddenFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/MobileQQFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/OfflineCacheFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/RecycleBinsFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/TelegramFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ThreemaFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ThumbnailsFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ViberFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/WeChatFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/WebViewCacheFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/WhatsAppBackupsFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/WhatsAppReceivedFilter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/WhatsAppSentFilter.kt
* If deletion fails, check if the file actually exists, if it doesn't, treat it as success.
* Pass all matches to the deletion routine and check (against all data) for any other files that were affected. If a top level folder fails to delete, sub folders may still have been deleted because `APath.deleteAll()` traveres the tree.
Closes https://github.com/d4rken-org/sdmaid-se/issues/1391
=> AppCleaner: Better handling for partial failure during deletion

app-common-io/src/main/java/eu/darken/sdmse/common/root/RootManager.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shizuku/ShizukuManager.kt
To prevent too frequent launches of Shizuku/Root based processes.
Closes #1407
=> Increase Root/Shizuku service timeouts

app/src/main/java/eu/darken/sdmse/main/ui/dashboard/DashboardViewModel.kt
This prevents showing it shortly and then being replaced by a setup prompt
=> Don't check and possibly show "Review me" nag until all tools are initialized

app/src/main/java/eu/darken/sdmse/App.kt, app/src/main/java/eu/darken/sdmse/common/coil/BitmapFetcher.kt, app/src/main/java/eu/darken/sdmse/common/coil/CoilModule.kt, app/src/main/java/eu/darken/sdmse/common/coil/CoilTempFiles.kt, app/src/main/java/eu/darken/sdmse/common/coil/PathPreviewFetcher.kt, app/src/test/java/eu/darken/sdmse/common/coil/CoilTempFilesTest.kt
When SD Maid generates thumbnails for large videos via coil, then large `.tmp` files can be created.
If SD Maid is killed before thumbnail generation has finished, then these `.tmp` can stay around until manually deleted.
This PR changes the path where these files are stored, and deletes any orphaned files `.tmp` files on the next app launch.
Also see https://github.com/coil-kt/coil/issues/2550
Thanks to [Martin](https://discord.com/channels/548521543039189022/1047079350157193236/1294625234447765547) for pointing this out :pray:
=> Fix video preview creating cache files that are not being deleted if the app is killed

app-common-io/src/main/aidl/eu/darken/sdmse/common/files/local/ipc/FileOpsConnection.aidl, app-common-io/src/main/aidl/eu/darken/sdmse/common/ipc/RemoteFileHandle.aidl, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/APathLookupExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/FileHandleWithCallbacks.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/GatewaySwitch.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/FileOpsHost.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/DocumentFileExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/ParcelFileDescriptorFileHandle.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/saf/SAFGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/ipc/RemoteFileHandleExtensions.kt, app-common/src/main/java/eu/darken/sdmse/common/sharedresource/SharedResource.kt, app/src/main/java/eu/darken/sdmse/common/coil/BitmapFetcher.kt, app/src/main/java/eu/darken/sdmse/common/coil/CoilTempFiles.kt, app/src/main/java/eu/darken/sdmse/common/coil/FileHandleImageSource.kt, app/src/main/java/eu/darken/sdmse/common/coil/PathPreviewFetcher.kt, app/src/main/java/eu/darken/sdmse/deduplicator/core/scanner/checksum/ChecksumSleuth.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/SuperfluousApksFilter.kt
Replace the previous sepperate read/write functions. Allows `Coil` to efficiently load video thumbnails. Improves SAF performance.
See #1434
See https://github.com/coil-kt/coil/issues/2550
=> Core: Support seekable file sources via `Okio.FileHandle`

app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt
Reported for a Pixel 8 Pro @ Android 15.
Couldn't reproduce myself
According to the log only happened to one app (SnapChat), but several apps before that didn't throw an NPE.
```java
java.lang.NullPointerException
at android.os.Parcel.createExceptionOrNull(Parcel.java:3248)
at android.os.Parcel.createException(Parcel.java:3226)
at android.os.Parcel.readException(Parcel.java:3209)
at android.os.Parcel.readException(Parcel.java:3151)
at android.app.usage.IStorageStatsManager$Stub$Proxy.queryStatsForPackage(IStorageStatsManager.java:505)
at android.app.usage.StorageStatsManager.queryStatsForPackage(StorageStatsManager.java:211)
at eu.darken.sdmse.appcontrol.core.AppControl.toAppInfo(Unknown Source:268)
at eu.darken.sdmse.appcontrol.core.AppControl.performScan(Unknown Source:351)
at …
```
=> Catch new NPE when querying app sizes on Android 15

app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/PublicDataCorpseFilter.kt
ADB level privileges are enough to scan `Android/data`, root isn't necessary.
=> CorpseFinder: Scan `Android/data` if Shizuku is available

app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/SdcardCorpseFilter.kt
The marker segments are prefix-free, so we also need to compare it with the prefix-free area information, otherwise we get no match. e.g.
Before: `{/storage/emulated/0/Android}.isAncestorOf(Android/cache)` returned false
Now: `{Android}.isAncestorOf(Android/cache)` returns true
=> CorpseFinder: Fix detection of nested corpses on public storage

app/src/main/assets/expendables/db_hidden_caches_files.json, app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/HiddenFilter.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/BaseFilterTestExtensions.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/HiddenFilterTest.kt
Better matching in general and specific matching for SHAREit `.status`.
Also see https://github.com/d4rken-org/sdmaid-se/pull/1452#issuecomment-2461209392
=> AppCleaner: Enhance hidden cache filter

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oneplus/OnePlusSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/vivo/VivoSpecs.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AccessibilityNodeExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/StepProcessor.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/UnclickableTargetException.kt
We need to pass a function to `nodeMapping` that is evaluated later.
The `when` evaluated immediately, when `isUnclickableButton=false`.
Also fixes the same issue for Vivo devices.
=> AppCleaner: Fix ACS based cache clearing not working on OnePlus and Vivo devices with Android 14/15

app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt
Keep PkgOps related resources alive for the whole operation.
Otherwise we see this when loading app data:
```java
22:03:37.784 SDMSE:Pkg:Ops                        V  querySizeStats(InstallId(pkgId=com.google.android.photopicker, userHandle=UserHandle2(handleId=0)),41217664-9172-527a-b3d5-edabb50a7d69)
22:03:37.785 SDMSE:Pkg:Ops                        V  querySizeStats(InstallId(pkgId=com.google.android.photopicker, userHandle=UserHandle2(handleId=0)),41217664-9172-527a-b3d5-edabb50a7d69) -> SizeStats(appBytes=524288, cacheBytes=0, externalCacheBytes=0, dataBytes=0)
22:03:37.785 SDMSE:Pkg:Ops                        V  isRunning(InstallId(pkgId=com.google.android.inputmethod.latin, userHandle=UserHandle2(handleId=0)), AUTO->ROOT)
22:03:37.785 SDMSE:Pkg:Ops:SR                     V …
```
=> AppControl: Improve scan performance

app/src/main/java/eu/darken/sdmse/systemcleaner/ui/customfilter/editor/TaggedInputView.kt
Long pressing a name criteria showed texts with "path", while long pressing a path criteria showed texts with "name". It was switched.
=> SystemCleaner: Fix custom filter criteria texts

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLabler.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AccessibilityNodeExtensions.kt
Check for false positives when matching "Storage".
Text may appear multiple times on large devices that use a dual pane layout.
Closes #1526
=> Improve ACS matching on tablets on landscape mode

app/src/main/res/values-pl/strings.xml
Bug in the translation, an extra placeholder was provided.
Fixes #1540
=> Fix crash in Polish language

app-common/src/main/java/eu/darken/sdmse/common/device/DeviceDetective.kt, app-common/src/main/java/eu/darken/sdmse/common/device/RomType.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleanerSettings.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/alcatel/AlcatelSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/coloros/ColorOSSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/flyme/FlymeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/honor/HonorSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/huawei/HuaweiSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsLabels.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/lge/LGESpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/nubia/NubiaSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oneplus/OnePlusSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/realme/RealmeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/samsung/SamsungSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/vivo/VivoSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/aosp/AOSPSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/samsung/SamsungSpecs.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/StepProcessor.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/AutomationExplorer.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/AutomationSpec.kt
* Fix ROM type override in general settings resetting
* Add ROM type detection for HyperOS 1.0 and 2.0
* Also fork the MIUI ACS logic and create a new HyperOS setup that we can expand in the future.
Fixes #1538
=> Fix ACS based cache deletion on HyperOS 2.0

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationSupportException.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/StepProcessor.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/AutomationCompatibilityException.kt, app/src/main/java/eu/darken/sdmse/main/ui/MainActivity.kt, app/src/main/java/eu/darken/sdmse/main/ui/MainViewModel.kt, app/src/main/res/values/strings.xml
Some users leave the ACS operations running for 60 minutes thinking it is working.
We now abort after 3 timeouts (if there have been no successful operations) and show a hint:
`SD Maid couldn’t figure out the screen layout. If this keeps happening, your language or setup might not be fully supported. Check for updates or reach out to me so I can fix it.`
=> Abort ACS operations early (with explanation) if ROM is not supported

app-common-io/src/main/java/eu/darken/sdmse/common/ipc/RemoteFileHandleExtensions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootServiceClient.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shell/ShellOps.kt, app-common-io/src/main/java/eu/darken/sdmse/common/user/UserManager2.kt, app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootConnectionReceiver.kt, app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootHostLauncher.kt, app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootIPC.kt, app-common-shell/src/main/java/eu/darken/flowshell/core/FlowShell.kt, app-common-shell/src/main/java/eu/darken/flowshell/core/FlowShellDebug.kt, app-common-shell/src/main/java/eu/darken/flowshell/core/cmd/FlowCmdShell.kt, app-common-shell/src/main/java/eu/darken/flowshell/core/process/FlowProcess.kt, app-common-shell/src/main/java/eu/darken/flowshell/core/process/FlowProcessExtensions.kt, app-common-shell/src/main/java/eu/darken/sdmse/common/shell/SharedShell.kt, app-common-shell/src/test/java/eu/darken/flowshell/core/process/FlowProcessTest.kt, app-common-shell/src/test/java/eu/darken/sdmse/common/shell/SharedShellTest.kt, app-common-test/src/main/java/testhelpers/coroutine/TestExtensions.kt, app-common/src/main/java/eu/darken/sdmse/common/JUnitLogger.kt, app-common/src/main/java/eu/darken/sdmse/common/debug/Bugs.kt, app-common/src/main/java/eu/darken/sdmse/common/sharedresource/Resource.kt, app-common/src/main/java/eu/darken/sdmse/common/sharedresource/SharedResource.kt, app-common/src/test/java/eu/darken/sdmse/common/sharedresource/SharedResourceTest.kt, app/src/test/java/eu/darken/sdmse/common/forensics/FileForensicsTest.kt
A rewrite of `SharedResource`, which is a class that manages the lifecycle of costly dependencies. These costly services are mostly Root and ADB related (launching a service in an extra process and connecting to it).
Replacing RXShell (#1529) made flaws within the old `SharedResource` visible, where we could trigger a race condition if one consumer gets a new lease, while another closes the last one.
I couldn't get the `Flow.shareIn` logic (on which the old `SharedResource` was based) to work. This is custom solution which gives me finer control over the behavior.
This should get us
* Less overhead when sharing resources
* No more random errors related to root or ADB :crossed_fingers: 
* Less resource use due to better re-use of the shared resource
* Now we have test coverage for this …
=> Overhaul internal resource management

app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/PkgRepo.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/common/areas/modules/DataAreaFactory.kt
`UserManager2.allUsers()` uses `ShellOps` internally to get current user info from the shell. Tools (like AppCleaner) and core classes like DataAreaFactory and PkgOps should keep ShellOps alive if they use it.
This prevents shell sessions from being repeatedly started meaning faster execution.
=> Fix `ShellOps` not being kept active by tools that use it

app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/AnalyticsFilter.kt, app/src/test/java/eu/darken/sdmse/systemcleaner/core/filter/stock/AnalyticsFilterTest.kt
Mostly analytics identifiers sourced from this paper
> Exploring Covert Third-party Identifiers through External Storage in the Android New Era
https://www.usenix.org/conference/usenixsecurity24/presentation/dong-zikan
=> SystemCleaner: Additional trash left behind by not so tidy apps

app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/sources/NotInstalledPkgsSource.kt, app-common/src/main/java/eu/darken/sdmse/common/ContextExtensions.kt, app/build.gradle.kts, app/src/foss/java/eu/darken/sdmse/common/updater/FossUpdateChecker.kt, app/src/main/java/eu/darken/sdmse/common/coil/PathPreviewFetcher.kt, app/src/main/java/eu/darken/sdmse/common/debug/recorder/core/RecorderModule.kt, app/src/main/java/eu/darken/sdmse/main/core/CurriculumVitae.kt, app/src/main/java/eu/darken/sdmse/main/core/release/ReleaseManager.kt, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml, buildSrc/src/main/java/ProjectConfigPlugin.kt, buildSrc/src/main/java/ProjectExtensions.kt
=> Compile against Android 15 Preview

app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/TelegramFilter.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/TelegramFilterTest.kt
The Telegram media files filter will now also include media related to "Stories"
=> AppCleaner: Include Telegram "Stories"

app-common-pkgs/src/main/java/eu/darken/sdmse/common/pkgs/PkgRepo.kt, app-common/src/main/java/eu/darken/sdmse/common/TimeExtensions.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControlScanTask.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppInfo.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppScan.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/SortSettings.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/usage/UsageInfo.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/usage/UsageTool.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListFragment.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListRowVH.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt, app/src/main/res/layout/appcontrol_list_fragment.xml, app/src/main/res/values/strings.xml
Allow sorting by screen time.
If screen time is selected as sortmode then each row will display the screen time and tertiary info.
Closes #1596
=> AppControl: Sort by screen time

PRIVACY_POLICY.md, _layouts/plain.html, app-common/src/main/java/eu/darken/sdmse/common/SdmSeLinks.kt
Switching to GitHub pages to deal with Google no longer allowing direct links to GitHub.
=> Update privacy policy layout

app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/custom/CustomFilterConfig.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/ui/customfilter/editor/CustomFilterEditorViewModel.kt
It shouldn't prompt for unsaved changes when creating a new filter and just exiting without changing anything.
=> SystemCleaner: Fix custom filter edit "unsaved changes" prompt

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/AppControlAutomation.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationHost.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/debug/DebugTaskModule.kt, app/src/main/java/eu/darken/sdmse/automation/ui/AutomationControlView.kt
* Refactor `changeOptions` and `updateProgress` to perform fewer UI updates.
* When affected by #1648, instead of hiding the overlay temporarily, let's just make it invisible to touch for a moment to pass through the tap gesture.
=> AppCleaner: Improve ACS performance

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/automation/core/animation/AnimationState.kt, app/src/main/java/eu/darken/sdmse/automation/core/animation/AnimationTool.kt, app/src/main/java/eu/darken/sdmse/common/OpsCounter.kt
Disable "window animation", "transition animation" and "global animations" through Shizuku when executing cache deletion through the accessibility service.
The original animation state is saved and restored after the accessibility operation finishes (or is cancelled).
=> AppCleaner: Faster accessibility operations by temporarily disabling animations (via Shizuku)

app/src/main/java/eu/darken/sdmse/automation/core/common/AutomationContextExtensions.kt
Via user email, affected device is `BLU/B135DL/B135DL:12/SP1A.210812.016/1738747440:user/release-keys`
Similar to #1178
=> AppCleaner: Skip locked system apps on Android 12 and 13 too

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/AppControlAutomation.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationHost.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationManager.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/AccessibilityNodeExtensions.kt, app/src/main/java/eu/darken/sdmse/automation/core/debug/DebugTask.kt, app/src/main/java/eu/darken/sdmse/automation/core/debug/DebugTaskModule.kt, app/src/main/java/eu/darken/sdmse/common/debug/DebugCardProvider.kt, app/src/main/java/eu/darken/sdmse/main/ui/dashboard/items/DebugCardVH.kt
Refactor the overlay logic:
* Explicitly add and remove the overlay for each task, without task, there can't be an added overlay
* Change screen availability check to set an `isOverlayExtraHidden` that prevents new tasks or option changes from making the overlay visible
* Only instantiate overlay when there is a task to reduce memory footprint when SD Maid is not active
Fixes #1670
=> ACS: Fix screen-overlay becoming visible again without active task

app/src/main/java/eu/darken/sdmse/automation/core/AutomationManager.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/setup/automation/AutomationSetupModule.kt
The internal logic did not re-check the ACS state, just calling it once on init. Now we listen to service changes and reload data.
=> AppControl: Fix ACS operations being unavailable if data is loaded before ACS is enabled

app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/features/Installed.kt, app-common/src/main/res/values/strings.xml, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/AutomationCompatibilityException.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/SpecGeneratorExtensions.kt
* Abort ACS operations on apex apps after failing to open settings one time, assume app has no settings screen
* Raise timeout limit until "SD Maid does not recognize your screen" to 10 apps
* Add device/os info to the error dialog (people keep sending me screenshots of it)
=> AppCleaner: Fix SD Maid hanging on certain system apps

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLabler.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLablerTest.kt
For ROMs where exact label matching fails, SD Maid will try to find the storage entry based on the storage size which is usually displayed on the entry. The "On the fly labler" did "contains" matching and in cases where "Data usage" had a summary like "1.80 MB ..." and the size to look for was "80 MB", we got a false positive match and SD Maid got stuck.
=> AppCleaner: Fix ACS navigating to "Data usage" instead of "Storage"

app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/automation/core/common/CrawledNode.kt
The new automation failure pop-up has shown that there are a lot more issues to fix where users previously thought it was just working slow.
Logging the screen state on errors is not enough, when recording a debug log, we need to log it everytime there is an event.
=> ACS: More details when debug logging

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/StorageEntryFinder.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/alcatel/AlcatelSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/coloros/ColorOSSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/honor/HonorSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/huawei/HuaweiSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/lge/LGESpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/nubia/NubiaSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oneplus/OnePlusSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/realme/RealmeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/samsung/SamsungSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/vivo/VivoSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/aosp/AOSPSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/automation/core/debug/DebugTaskModule.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/SpecGeneratorExtensions.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/automation/specs/OnTheFlyLablerTest.kt
Previously we just went with the first "Storage" entry we found, but sometimes there are more, and the first one is not the one we want. This is the case on tablets or large screen devices, where the settings UI uses a "double pane" layout. Here the left pane will also contain a "Storage" entry that takes us to the whole devices storage overview.
Fixes #1720
=> AppCleaner: Smarter "Storage" entry finding (fixes false-positives on tablet layouts)

app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt
Some Xiaomi devices with HyperOS2 are still getting stuck at the manual gesture to click the Clear cache button. This is my best guess, the delay is not long enough. The system UI has not adapted to the new options yet and the click is not going through.
=> ACS: Increase delay after changing overlay options

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/AppCleanerSpecGeneratorExtensions.kt
Previously all buttons had to be disabled for this abort condition to be met this was to strict and caused SD Maid to hang longer than necessary.
=> AppCleaner: Skip system apps with just a locked clear cache button

app/src/main/java/eu/darken/sdmse/appcleaner/core/forensics/filter/BugReportingFilter.kt, app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/BugReportingFilterTest.kt
Adds support for identifying and filtering crashlytics v2 related files.
=> AppCleaner: Add crashlytics v2 support to bugreporting filter

app/src/main/java/eu/darken/sdmse/setup/storage/StorageSetupModule.kt
Tested this on an emulator. Since Android 13 (API33), AndroidTV also needs to request `MANAGE_EXTERNAL_STORAGE`. This is a bit later than on phones where we needed that since Android 11 (API30).
Could already be manually granted via settings, but now the setup card takes the user to the right menu.
=> Setup: Ask for MANAGE_EXTERNAL_STORAGE on AndroidTVs running Android 13+.

app-common/src/main/java/eu/darken/sdmse/common/error/LocalizedError.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/SecurityCenterMissingPermissionException.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/InvalidSystemStateException.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/ScreenUnavailableException.kt, app/src/main/java/eu/darken/sdmse/common/error/ErrorDialog.kt, app/src/main/res/values/strings.xml
No idea how this happens but have seen this in a few reports now.
For some reason, on some devices, the security center app is missing that permission, which causes the `Clear data` button to be disabled, and thus ACS based cache clearing fails.
This change tries to detect that circumstance and shows an error dialog explaining it.
=> AppCleaner: Detect if `com.miui.securitycenter` is missing the `GET_USAGE_STATS` permission

app-common/src/main/java/eu/darken/sdmse/common/debug/DebugExtensions.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/LabelDebugger.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/alcatel/AlcatelSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/coloros/ColorOSSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/flyme/FlymeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/honor/HonorSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/huawei/HuaweiSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/nubia/NubiaSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oneui/OneUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oxygenos/OxygenOSSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/realme/RealmeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/vivo/VivoSpecs.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/SpecGeneratorExtensions.kt
Improve the search for window labels during automation by:
- Adding a check for the application label resource ID.
- Retrieving localized application labels for comparison.
- Visualizing window identifiers in debug logs.
Fixes #1771
=> AppCleaner: Improve window label search, handling of different locales and ZWSP

app/src/main/java/eu/darken/sdmse/scheduler/core/SchedulerManager.kt, buildSrc/src/main/java/Dependencies.kt
Possibly fixing this:
```java
Exception android.app.RemoteServiceException$ForegroundServiceDidNotStopInTimeException: A foreground service of type dataSync did not stop within its timeout: ComponentInfo{eu.darken.sdmse/androidx.work.impl.foreground.SystemForegroundService}
at android.app.ActivityThread.generateForegroundServiceDidNotStopInTimeException (ActivityThread.java:2932)
at android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:2894)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException (Unknown Source)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:3255)
at android.os.Handler.dispatchMessage (Handler.java:118)
at android.os.Looper.loopOnce (Looper.java:237)
at android.os.Looper.loop (Looper.java:325)
at …
```
=> Dependency: Update WorkManager to 2.10.1 to fix possible background crash on updates

app/src/main/java/eu/darken/sdmse/automation/core/specs/SpecGeneratorExtensions.kt
Added logging to the `waitForWindowByIdentifier` function to indicate whether the window check passed or failed.
=> Automation: Log window check failure

app-common/src/main/java/eu/darken/sdmse/common/device/DeviceDetective.kt, app-common/src/main/java/eu/darken/sdmse/common/device/RomType.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/doogee/DoogeeSpecs.kt
Add `DOOGEE` as a recognized RomType and implement a basic AppCleaner spec for it. Doogee ROMs are based on AOSP, so the spec largely mirrors the AOSP one.
Fixes #1781
=> AppCleaner: ACS support for `DOOGEE` ROMs/devices

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationHost.kt, app/src/main/java/eu/darken/sdmse/automation/core/AutomationService.kt, app/src/main/java/eu/darken/sdmse/automation/core/debug/DebugTaskModule.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/SpecGeneratorExtensions.kt
Introduce a `Snapshot` data class to wrap `AccessibilityEvent`s within the `AutomationService`. This `Snapshot` now includes a unique ID.
Modify the event flow exposed by `AutomationHost` to emit `Snapshot`s instead of raw `AccessibilityEvent`s. Update usages in `HyperOsSpecs`, `SpecGeneratorExtensions`, and `DebugTaskModule` to extract the event from the `Snapshot`.
Implement debug logging for screen snapshots in `AutomationService`. This includes logging the snapshot ID, the event, and the crawled node hierarchy, with a timeout to prevent blocking. This logging is enabled only in debug builds.
=> Refactor: Add AutomationService.Snapshot and debug logging

app-common/src/main/java/eu/darken/sdmse/common/device/DeviceDetective.kt, app-common/src/main/java/eu/darken/sdmse/common/device/RomType.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/LabelDebugger.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPLabels.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPLabels29Plus.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oukitel/OukitelSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/aosp/AOSPLabels.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/oukitel/OukitelSpecs.kt
Added a new ROM type `OUKITEL` to the `RomType` enum and the `DeviceDetective`. Implemented specific automation specifications for Oukitel devices in both AppControl and AppCleaner, based on AOSP behavior.
Fixes #1777
=> DeviceDetective, AppControl, AppCleaner: Add OUKITEL ROM type and specs

buildSrc/src/main/java/Versions.kt
Downgrade Navigation Core to 2.8.9
Navigation Core version 2.9.0 seems to have a bug causing an `ConcurrentModificationException`.
See:
https://issuetracker.google.com/issues/188860458
https://issuetracker.google.com/issues/417784831
Fixes #1789
=> Fix random crash when navigating screens

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/aosp/AOSPSpecs.kt
The "Clear Cache" button may be a LinearLayout containing the text label on some AOSP variants. This commit adds logic to find the clickable parent in such cases. Overall this aligns the "Clear cache" button layout with that of the "Force stop" button.
Fixes #1794
=> AppCleaner: Fix finding of "Clear Cache" button on Android 16 Beta Q1

app-common/src/main/res/values/strings.xml, app/src/main/java/eu/darken/sdmse/appcleaner/core/InaccessibleDeleter.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheTask.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/AppControlAutomation.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/AutomationTimeoutException.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/AutomationExplorer.kt, app/src/main/res/values/strings.xml
This commit introduces a new `AutomationTimeoutException` to specifically handle cases where automation tasks time out.
Additionally, the `AutomationCompatibilityException` and the new `AutomationTimeoutException` now include an action to report a bug, guiding users to the relevant wiki page.
The AppCleaner's `ClearCacheModule` has been updated to:
- Properly handle and log `AutomationTimeoutException`.
- Limit the number of consecutive timeouts before considering it a compatibility issue, specifically when no successful operations have occurred.
- Track individual item failures during inaccessible cache deletion and include them in the result, even if the overall operation is cancelled by the user.
String resources have been updated for clarity and to include a "Report bug" action label.
=> Automation: Introduce AutomationTimeoutException and improve error reporting

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/automation/core/errors/AutomationOverlayException.kt, app/src/main/java/eu/darken/sdmse/automation/core/specs/AutomationExplorer.kt, app/src/main/res/values/strings.xml
Introduces a specific exception for cases where displaying the automation overlay fails due to a `WindowManager.BadTokenException`. This exception provides a localized error message to the user, suggesting a reboot as a potential solution.
Implements #1787
=> Automation: Add AutomationBadTokenException

app-common-pkgs/src/main/res/values-vi/strings.xml
This commit adds Vietnamese translations for the following strings:
- `pkgrepo_invalid_inventory_error_title`
- `pkgrepo_invalid_inventory_error_description`
=> Add Vietnamese translation for pkgrepo error strings

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/alcatel/AlcatelSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/coloros/ColorOSSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/doogee/DoogeeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/flyme/FlymeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/honor/HonorSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/huawei/HuaweiSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/lge/LGESpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/nubia/NubiaSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oneui/OneUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oukitel/OukitelSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/oxygenos/OxygenOSSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/realme/RealmeSpecs.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/vivo/VivoSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/androidtv/AndroidTVSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/aosp/AOSPSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/hyperos/HyperOsSpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/miui/MIUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/oneui/OneUISpecs.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/specs/oukitel/OukitelSpecs.kt
This helps with debugging when automation fails as the target package is now part of the step description.
=> Automation: Add package name to internal step description

app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/ClearCacheModule.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/automation/AppControlAutomation.kt
This change refactors the exception handling logic in `AppControlAutomation.kt` and `ClearCacheModule.kt` to use a `when` statement for better readability and consistency.
Key changes:
- Replaced multiple `catch` blocks with a single `catch (e: Exception)` block.
- Used a `when` statement within the `catch` block to handle different exception types.
- Ensured consistent logging and error reporting across both modules.
- Maintained existing logic for specific exceptions like `AutomationTimeoutException`, `UserCancelledAutomationException`, and `PlanAbortException`.
- Re-throw unhandled critical exceptions like `InvalidSystemStateException`, `AutomationOverlayException`, and `UnsupportedOperationException` after logging.
=> Automation: Unify exception handling in AppControl and AppCleaner

app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt
The `itemCount` for inaccessible items was incorrectly hardcoded to `1`, which would be wrong if multiple files contributed to the inaccessible size. This change removes the incorrect `itemCount` update, ensuring the `totalSize` and `publicSize` are correctly adjusted after deleting inaccessible files.
=> AppCleaner: Correctly update inaccessible item count after deletion

app/src/main/java/eu/darken/sdmse/systemcleaner/ui/customfilter/editor/CustomFilterEditorViewModel.kt
Ensure live search operations run on the IO dispatcher. The crawler may block too many coroutines.
=> SystemCleaner: Fix custom filter editor UI hanging due to thread exhaustion

app-common-io/src/main/java/eu/darken/sdmse/common/files/local/LocalGateway.kt, app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app-common-io/src/main/java/eu/darken/sdmse/common/shell/ShellOps.kt, app-common/src/main/java/eu/darken/sdmse/common/sharedresource/SharedResourceExtensions.kt, app/src/main/java/eu/darken/sdmse/analyzer/core/Analyzer.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentFragment.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentItemEvents.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentItemVH.kt, app/src/main/java/eu/darken/sdmse/analyzer/ui/storage/content/ContentViewModel.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt, app/src/main/java/eu/darken/sdmse/common/forensics/FileForensics.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/CorpseFinder.kt, app/src/main/java/eu/darken/sdmse/deduplicator/core/Deduplicator.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCleaner.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCrawler.kt
- Always enable selection for all items, regardless of accessibility.
- Disable "Delete" and "Create Filter" actions in the CAB menu if any selected item is inaccessible.
- When a single item is excluded, the "View" action in the Snackbar now directly opens the created exclusion instead of navigating to the general exclusions list.
- Refactored event handling for exclusion creation to pass the affected content items, enabling more specific UI updates.
Implements #1643
Draft: Check #1644 and #1645
=> Storage Analyzer: Improve UX for exclusion creation and selection

app/src/main/java/eu/darken/sdmse/appcleaner/core/scanner/AppScanner.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/SystemCleanerSettings.kt, app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/stock/ThumbnailsFilter.kt, app/src/main/res/drawable/ic_thumb_up_24.xml, app/src/main/res/xml/preferences_systemcleaner.xml, app/src/test/java/eu/darken/sdmse/systemcleaner/core/filter/stock/ThumbnailsFilterTest.kt
This commit introduces a new filter to SystemCleaner for deleting thumbnail files and folders (e.g., `.thumbnails`).
The filter targets SDCARD, PUBLIC_MEDIA, and PORTABLE data areas. It is disabled by default.
A corresponding setting and UI element have been added to the SystemCleaner preferences. Tests for the new filter have also been included.
Implements #1522
=> SystemCleaner: Add Thumbnails filter

app-common/src/main/java/eu/darken/sdmse/common/device/DeviceDetective.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt
This commit refactors the MIUI automation specification to simplify node selection and improve robustness across different MIUI versions.
Previously, the automation differentiated between MIUI versions (10/11 vs 12+) to determine if a node was a `TextView` or a `Button` and whether to find a clickable parent.
This has been simplified:
- The automation now primarily looks for nodes with text matching "Clear data" or "Clear cache".
- If the found node is not clickable, it will attempt to find a clickable parent.
- The explicit version check (`isMiui12Plus`) has been removed.
Fixes #1814
=> AppCleaner: Simplify MIUI automation logic

app-common/src/main/java/eu/darken/sdmse/common/device/DeviceDetective.kt
UGOOS devices, while sometimes marketed as TV boxes, run a phone-style AOSP ROM rather than Android TV. This change correctly identifies them as `RomType.AOSP`.
Closes #1826
=> DeviceDetective: Detect UGOOS devices as AOSP

app/src/main/java/eu/darken/sdmse/common/MimeTypeTool.kt
Improve MIME type determination from file extension
This commit refactors the `determineMimeType` function in `MimeTypeTool.kt`.
The file extension is now extracted by taking the substring after the last dot in the filename and converting it to lowercase. This approach is more robust than `MimeTypeMap.getFileExtensionFromUrl()` for determining the extension.
Reported by @MeloriTensei, Thanks!
=> Deduplicator: Fix previews and "common" file type detection

app-common/src/main/java/eu/darken/sdmse/common/device/RomType.kt, app-common/src/test/java/eu/darken/sdmse/common/device/RomTypeTest.kt, app/src/main/java/eu/darken/sdmse/common/preferences/PreferenceExtensions.kt
This commit updates the `RomType` enum to improve its JSON serialization and deserialization using Moshi.
`PreferenceExtensions.kt` has been updated to correctly derive `entryValues` for enum preferences by using the preference's writer and removing surrounding quotes, aligning it with the JSON representation.
New tests (`RomTypeTest`) have been added to verify that the `@Json(name = "...")` annotations are correctly used, ensuring that, for example, `RomType.FUNTOUCHOS` serializes to `"VIVO"` and vice-versa.
=> Fix crash when selecting certain ROM-types

app-common-io/src/main/java/eu/darken/sdmse/common/pkgs/pkgops/PkgOps.kt, app/src/main/java/eu/darken/sdmse/setup/saf/SAFSetupModule.kt
Use normal query for current user in AUTO mode
When `PkgOps.queryPkg` is called with `Mode.AUTO` and the `userHandle` matches the current user, this change optimizes the query to use the "normal" (non-root) path. This avoids unnecessary root operations for the common case of querying packages for the active user.
=> Setup: Fix crash on Android 11/12

app/build.gradle.kts, app/src/gplay/java/eu/darken/sdmse/common/upgrade/core/billing/client/BillingConnection.kt, app/src/gplay/java/eu/darken/sdmse/common/upgrade/core/billing/client/BillingConnectionProvider.kt
This commit updates the Google Play Billing Library from version 6.2.1 to 8.0.0. It adapts the code to the API changes in `queryProductDetailsAsync` and `enablePendingPurchases`.
=> Upgrade Google Billing Library to v8

app-common-io/src/main/java/eu/darken/sdmse/common/files/PathExceptions.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/LocalPathLookupIPCFlow.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/LocalPathLookupResult.kt, app-common-io/src/main/java/eu/darken/sdmse/common/files/local/ipc/LocalPathLookupResultsIPCWrapper.kt
Propagate exceptions via LocalPathLookupResult to prevent IPC from crashing. Client-side should get ReadException now instead of DeadObjectException.
This commit modifies the IPC mechanism for `LocalPathLookup` to also transmit exceptions. It introduces a sealed class `LocalPathLookupResult` which can be either a `Success` (containing the `LocalPathLookup`) or an `Error` (containing exception details).
The `LocalPathLookupIPCFlow` is updated to serialize and deserialize `LocalPathLookupResult` instances, allowing exceptions from the producing flow to be re-thrown in the collecting flow. `PathException` and its subclasses are now annotated with `@Keep`.
=> Prevent read errors on non-existing directories from crashing Shizuku/Root services.

app-common/src/main/java/eu/darken/sdmse/common/datastore/PreferenceStoreMapper.kt
Fixes crash when accessing string keys with a null value
- Throw `NotImplementedError` directly in `byKey` if a `DataStoreValue` for the given key is not found.
- Remove redundant `NotImplementedError` throws in getter/setter methods as `byKey` now handles this.
- Simplify getter/setter logic by removing nullable checks, relying on `byKey`'s non-null return or exception.
=> Refactor: Improve PreferenceStoreMapper key lookup

app/src/main/java/eu/darken/sdmse/setup/SetupFragment.kt
The fastscroll feature is not necessary for the setup list and has been disabled to simplify the UI.
Fixes #1881
=> Setup: Disable fastscroll in setup list

app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScanner.kt, app/src/main/java/eu/darken/sdmse/setup/saf/SAFSetupModule.kt
Seems to be specific behavior to Android 12 and Samsung's "Dual Messenger".
SD Maid fails to get the internal storage because there are two internal storages returned by the system:
SDM wants to map this (internalId is "null"):
scan(DeviceStorage(id=StorageId(internalId=null, externalId=41217664-9172-527a-b3d5-edabb50a7d69), label=CachedCaString("Primary storage"), type=PRIMARY, hardware=BUILT_IN, spaceCapacity=137438953472, spaceFree=36861681664, setupIncomplete=false))
To these (both have uuid "null"):
StorageVolumeX(uuid=null, directory=/storage/emulated/0, userlabel=Internal shared storage, volumeX=StorageVolume: Internal shared storage, rootUri=content://com.android.externalstorage.documents/root/primary) against LocalPath(/storage/emulated/0/Android/data) StorageVolumeX(uuid=null, …
=> Analyzer: Fix storage analyzer tripping up on Samsung's "Dual Messenger"

app/src/main/java/eu/darken/sdmse/appcontrol/core/AppControl.kt, app/src/main/java/eu/darken/sdmse/appcontrol/core/AppScan.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/AppControlListViewModel.kt, app/src/main/java/eu/darken/sdmse/appcontrol/ui/list/actions/AppActionViewModel.kt, app/src/main/res/navigation/main_nav.xml
On rooted or Shizuku devices, SD Maid has access to app installs from other users/profiles.
Normally only the apps of the current user are displayed in the list.
The update logic after enabling/disabling an app, did not filter out app data from other users.
So after changing the enabled/disabled state of an app that was installed for other users, suddenly duplicate entries appeared that couldn't be opened.
These extra entries will no longer appear, and if they do, they will not be openable.
I'm considering enabling multi user display in another feature PR.
Fixes #1907
=> AppControl: Fix duplicate entries when changing app states

app/src/main/java/eu/darken/sdmse/common/areas/modules/dalvik/DalvikProfileModule.kt, app/src/main/java/eu/darken/sdmse/common/forensics/FileForensics.kt, app/src/main/java/eu/darken/sdmse/common/forensics/csi/dalvik/DalvikDexCSI.kt, app/src/main/java/eu/darken/sdmse/common/forensics/csi/dalvik/tools/DexStringsCheck.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppAsecFileCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppLibCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/AppSourcePrivateCorpseFilter.kt, app/src/main/java/eu/darken/sdmse/corpsefinder/core/filter/DalvikCorpseFilter.kt, app/src/test/java/eu/darken/sdmse/common/forensics/FileForensicsTest.kt, app/src/test/java/eu/darken/sdmse/common/forensics/csi/BaseCSITest.kt, app/src/test/java/eu/darken/sdmse/common/forensics/csi/dalvik/DalvikDexCSITest.kt
Additional sanity check via `DexStringsCheck`, checks the cmd --comment field of `.dex` files. Faster than the APK check, so we gain some speed here.
See #1612
=> CorpseFinder: Support scanning dalvik-cache on rooted Android 15+ ROMs

app/src/main/res/layout/debug_recorder_activity.xml
This commit addresses a layout issue in the Debug Recorder where the content was not fully scrollable.
Key changes:
- Set `android:fillViewport="true"` on the `NestedScrollView` to allow the content to fill the scroll view's viewport, enabling scrolling even if the content is smaller than the viewport.
- Adjusted padding on the inner `LinearLayout` and added `minHeight`, `paddingBottom`, and `clipToPadding` to the `RecyclerView` (`@id/list`) to ensure all items are visible and scrollable, particularly the last items which were previously obscured.
=> Ensure full scrollability in Debug Recorder

app/src/test/java/eu/darken/sdmse/common/sieve/SegmentCriteriumTest.kt, app/src/test/java/eu/darken/sdmse/systemcleaner/core/filter/sieve/SystemCrawlerSieveTest.kt
`basePath.child("abc", "/")` created an invalid test case as `/` can not be the name of a child.
This commit removes a redundant test case from `SystemCrawlerSieveTest` that was already covered by `SegmentCriteriumTest`. It also adds new test cases to `SegmentCriteriumTest` to verify correct matching of paths ending with a separator, especially when `allowPartial = true`.
=> Test: Refine `SegmentCriterium` path matching

app/src/main/AndroidManifest.xml, app/src/main/java/eu/darken/sdmse/App.kt, app/src/main/java/eu/darken/sdmse/main/core/GeneralSettings.kt, app/src/main/java/eu/darken/sdmse/main/core/shortcuts/AppShortcut.kt, app/src/main/java/eu/darken/sdmse/main/core/shortcuts/ShortcutManager.kt, app/src/main/java/eu/darken/sdmse/main/ui/MainActivity.kt, app/src/main/java/eu/darken/sdmse/main/ui/shortcuts/ShortcutActivity.kt, app/src/main/res/drawable/ic_shortcut_apps.xml, app/src/main/res/drawable/ic_shortcut_delete.xml, app/src/main/res/drawable/ic_shortcut_onetap.xml, app/src/main/res/drawable/ic_shortcut_scan.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_general.xml
Implements dynamic app shortcuts that appear when long-pressing the app icon:
• AppControl shortcut: Direct access to app management (free)
• Scan + Delete shortcut: One-tap cleaning (Pro feature, toggleable)
Key features:
- Dynamic shortcuts that update based on user settings
- Pro version check with upgrade flow for scan/delete shortcut
- Headless task execution without opening dashboard UI
- Settings toggle in General Settings → Shortcuts
- Respects existing one-click tool preferences
- Uses OneClick tasks for consistent behavior
Closes https://github.com/d4rken-org/sdmaid-se/issues/1902
=> Feature: Add app shortcuts for quick access

app/src/main/res/layout/systemcleaner_list_item.xml
The extra info text in SystemCleaner list items can now span up to 3 lines instead of being restricted to a single line. `tools:text` was also updated for better preview.
=> SystemCleaner: Allow up to 3 lines for SystemCleaner item extra info

app-common/src/main/java/eu/darken/sdmse/common/StringExtensions.kt, app/src/main/java/eu/darken/sdmse/deduplicator/ui/details/cluster/elements/ChecksumGroupFileVH.kt, app/src/main/java/eu/darken/sdmse/deduplicator/ui/details/cluster/elements/PHashGroupFileVH.kt, app/src/main/java/eu/darken/sdmse/deduplicator/ui/list/DeduplicatorListLinearSubAdapter.kt, app/src/main/res/layout/deduplicator_cluster_element_checksumgroup_file.xml, app/src/main/res/layout/deduplicator_cluster_element_phashgroup_file.xml, app/src/main/res/layout/deduplicator_list_linear_sub_item.xml
Separate filename display from full path in duplicate file listings for better readability. File names are now shown prominently with ellipsis in the middle, while paths are displayed below with start ellipsis to show relevant folder context.
Changes:
- Add replaceLast() string extension for proper filename removal from paths
- Update ChecksumGroupFileVH and PHashGroupFileVH to use split display
- Modify DeduplicatorListLinearSubAdapter to use replaceLast() instead of replace()
- Update XML layouts to show filename and path as separate text views
- Improve ellipsis strategies: middle for names, start for paths
This addresses user feedback about file identification being difficult when only seeing truncated full paths.
=> Deduplicator: Improve file display with separate name and path

app/src/main/java/eu/darken/sdmse/appcleaner/core/AppCleaner.kt, app/src/main/java/eu/darken/sdmse/appcleaner/core/tasks/AppCleanerOneClickTask.kt, app/src/main/java/eu/darken/sdmse/main/ui/shortcuts/ShortcutActivity.kt
If ACS operations are launched via shortcut, don't return to SD Maid at the end.
=> Shortcuts: Don't return to app if AppCleaner uses ACS

app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/AppJunkViewModel.kt, app/src/main/java/eu/darken/sdmse/appcleaner/ui/details/appjunk/elements/AppJunkElementFileCategoryVH.kt, app/src/main/res/layout/appcleaner_appjunk_element_file_category.xml
Users can now collapse and expand file categories in the AppCleaner details view to better navigate through long lists of files. This helps prevent accidental deletions and improves the user experience when reviewing files.
- Added collapse state tracking in AppJunkViewModel
- File categories now have a collapse/expand button that toggles visibility
- Category headers remain visible with item count and size information
- Icons change between expand_less (expanded) and expand_more (collapsed)
- Files under collapsed categories are hidden from the list
This addresses user concerns about navigating lists with many items (e.g., 103 items in public cache) and reduces the risk of accidentally deleting important files.
Closes #1951
=> AppCleaner: Add collapse/expand functionality for file categories

app-common/src/main/java/eu/darken/sdmse/common/permissions/Permission.kt, app-common/src/main/java/eu/darken/sdmse/common/permissions/PermissionExtensions.kt
On HONOR devices (and some MIUI/HyperOS ROMs), AppOpsManager.checkOpNoThrow() returns MODE_DEFAULT instead of MODE_ALLOWED even when the PACKAGE_USAGE_STATS permission toggle is enabled in system settings.
Previously, SD Maid only checked for MODE_ALLOWED, causing it to incorrectly report the permission as denied on HONOR devices, leading to persistent "Grant access" prompts.
Changes:
- Handle all AppOpsManager modes (ALLOWED, IGNORED, ERRORED, DEFAULT, unknown)
- For MODE_DEFAULT, fallback to checkSelfPermission() as recommended by Android docs
- Add comprehensive VERBOSE logging to track permission check results
- Consolidate MODE_IGNORED and MODE_ERRORED handling (both deny permission)
This follows the official Android recommendation for handling MODE_DEFAULT found in Stack Overflow …
=> General: Fix usage statistics permission detection on HONOR devices

app/src/main/java/eu/darken/sdmse/common/picker/PickerFragment.kt
Dynamically set the toolbar navigation icon to a "close" icon when at the root directory and a "back" icon otherwise.
Noticed during debugging #1974
=> Picker: Update toolbar navigation icon
